INSERT INTO masterdata_items (category_id, code, name, sort_order, is_system, status, metadata)
SELECT c.id, v.code, v.name, v.sort_order, FALSE, 'ACTIVE', v.metadata::jsonb
FROM masterdata_categories c
CROSS JOIN (VALUES
    ('POSITION_001', 'BS_ Foreman - LM Roll Mill', 1, '{"legacy_sap_code": "BS_ Foreman - LM Roll Mill"}'),
    ('POSITION_002', 'BS_ SH - Converting', 2, '{"legacy_sap_code": "BS_ SH - Converting"}'),
    ('POSITION_003', 'BS_ Sr. Staff - Quality & Food Safety Mg', 3, '{"legacy_sap_code": "BS_ Sr. Staff - Quality & Food Safety Mg"}'),
    ('POSITION_004', 'BS_ Sr. Technician - LM Roll Mill', 4, '{"legacy_sap_code": "BS_ Sr. Technician - LM Roll Mill"}'),
    ('POSITION_005', 'BS_Analyst - PQC', 5, '{"legacy_sap_code": "BS_Analyst - PQC"}'),
    ('POSITION_006', 'BS_Analyst - PQC Sby', 6, '{"legacy_sap_code": "BS_Analyst - PQC Sby"}'),
    ('POSITION_007', 'BS_Ass. Instructor - Administration 2.3.', 7, '{"legacy_sap_code": "BS_Ass. Instructor - Administration 2.3."}'),
    ('POSITION_008', 'BS_Ass. Instructor - Administration BBC', 8, '{"legacy_sap_code": "BS_Ass. Instructor - Administration BBC"}'),
    ('POSITION_009', 'BS_Ass. Manager - Accounts Payable', 9, '{"legacy_sap_code": "BS_Ass. Manager - Accounts Payable"}'),
    ('POSITION_010', 'BS_Ass. Manager - Accounts Receivable', 10, '{"legacy_sap_code": "BS_Ass. Manager - Accounts Receivable"}'),
    ('POSITION_011', 'BS_Ass. Manager - Area Sales 1.1.2', 11, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 1.1.2"}'),
    ('POSITION_012', 'BS_Ass. Manager - Area Sales 1.2.1', 12, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 1.2.1"}'),
    ('POSITION_013', 'BS_Ass. Manager - Area Sales 1.2.2', 13, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 1.2.2"}'),
    ('POSITION_014', 'BS_Ass. Manager - Area Sales 2.2.2', 14, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 2.2.2"}'),
    ('POSITION_015', 'BS_Ass. Manager - Area Sales 2.3.2', 15, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 2.3.2"}'),
    ('POSITION_016', 'BS_Ass. Manager - Area Sales 3.1.1', 16, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 3.1.1"}'),
    ('POSITION_017', 'BS_Ass. Manager - Area Sales 3.1.2', 17, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 3.1.2"}'),
    ('POSITION_018', 'BS_Ass. Manager - Area Sales 3.2.2', 18, '{"legacy_sap_code": "BS_Ass. Manager - Area Sales 3.2.2"}'),
    ('POSITION_019', 'BS_Ass. Manager - Biscuit', 19, '{"legacy_sap_code": "BS_Ass. Manager - Biscuit"}'),
    ('POSITION_020', 'BS_Ass. Manager - Business Planning', 20, '{"legacy_sap_code": "BS_Ass. Manager - Business Planning"}'),
    ('POSITION_021', 'BS_Ass. Manager - Competency Management', 21, '{"legacy_sap_code": "BS_Ass. Manager - Competency Management"}'),
    ('POSITION_022', 'BS_Ass. Manager - Credit, Billing & Coll', 22, '{"legacy_sap_code": "BS_Ass. Manager - Credit, Billing & Coll"}'),
    ('POSITION_023', 'BS_Ass. Manager - Data Analysis, Plannin', 23, '{"legacy_sap_code": "BS_Ass. Manager - Data Analysis, Plannin"}'),
    ('POSITION_024', 'BS_Ass. Manager - Disbursement', 24, '{"legacy_sap_code": "BS_Ass. Manager - Disbursement"}'),
    ('POSITION_025', 'BS_Ass. Manager - FPS & Logistics Area 1', 25, '{"legacy_sap_code": "BS_Ass. Manager - FPS & Logistics Area 1"}'),
    ('POSITION_026', 'BS_Ass. Manager - Gate Office', 26, '{"legacy_sap_code": "BS_Ass. Manager - Gate Office"}'),
    ('POSITION_027', 'BS_Ass. Manager - General Accounting', 27, '{"legacy_sap_code": "BS_Ass. Manager - General Accounting"}'),
    ('POSITION_028', 'BS_Ass. Manager - General Affairs', 28, '{"legacy_sap_code": "BS_Ass. Manager - General Affairs"}'),
    ('POSITION_029', 'BS_Ass. Manager - IT Operations - Sby', 29, '{"legacy_sap_code": "BS_Ass. Manager - IT Operations - Sby"}'),
    ('POSITION_030', 'BS_Ass. Manager - Inventory & Fixed Asse', 30, '{"legacy_sap_code": "BS_Ass. Manager - Inventory & Fixed Asse"}'),
    ('POSITION_031', 'BS_Ass. Manager - Legal - Jkt', 31, '{"legacy_sap_code": "BS_Ass. Manager - Legal - Jkt"}'),
    ('POSITION_032', 'BS_Ass. Manager - PPIC', 32, '{"legacy_sap_code": "BS_Ass. Manager - PPIC"}'),
    ('POSITION_033', 'BS_Ass. Manager - PPIC - Jkt', 33, '{"legacy_sap_code": "BS_Ass. Manager - PPIC - Jkt"}'),
    ('POSITION_034', 'BS_Ass. Manager - PPIC - Sby', 34, '{"legacy_sap_code": "BS_Ass. Manager - PPIC - Sby"}'),
    ('POSITION_035', 'BS_Ass. Manager - PQC - Jkt', 35, '{"legacy_sap_code": "BS_Ass. Manager - PQC - Jkt"}'),
    ('POSITION_036', 'BS_Ass. Manager - PQC Sby', 36, '{"legacy_sap_code": "BS_Ass. Manager - PQC Sby"}'),
    ('POSITION_037', 'BS_Ass. Manager - Pest Control', 37, '{"legacy_sap_code": "BS_Ass. Manager - Pest Control"}'),
    ('POSITION_038', 'BS_Ass. Manager - Planning & Allocation', 38, '{"legacy_sap_code": "BS_Ass. Manager - Planning & Allocation"}'),
    ('POSITION_039', 'BS_Ass. Manager - Quality Assurance-Jkt', 39, '{"legacy_sap_code": "BS_Ass. Manager - Quality Assurance-Jkt"}'),
    ('POSITION_040', 'BS_Ass. Manager - Quality Assurance-Sby', 40, '{"legacy_sap_code": "BS_Ass. Manager - Quality Assurance-Sby"}'),
    ('POSITION_041', 'BS_Ass. Manager - Raw Material Planning', 41, '{"legacy_sap_code": "BS_Ass. Manager - Raw Material Planning"}'),
    ('POSITION_042', 'BS_Ass. Manager - SME & Market Developme', 42, '{"legacy_sap_code": "BS_Ass. Manager - SME & Market Developme"}'),
    ('POSITION_043', 'BS_Ass. Manager - Sales Export & Admin.', 43, '{"legacy_sap_code": "BS_Ass. Manager - Sales Export & Admin."}'),
    ('POSITION_044', 'BS_Ass. Manager - Storage - Sby', 44, '{"legacy_sap_code": "BS_Ass. Manager - Storage - Sby"}'),
    ('POSITION_045', 'BS_Ass. Manager - Storage Operations', 45, '{"legacy_sap_code": "BS_Ass. Manager - Storage Operations"}'),
    ('POSITION_046', 'BS_Ass. Manager - Treasury', 46, '{"legacy_sap_code": "BS_Ass. Manager - Treasury"}'),
    ('POSITION_047', 'BS_Ass. Manager-Key  Account Eastern CBP', 47, '{"legacy_sap_code": "BS_Ass. Manager-Key  Account Eastern CBP"}'),
    ('POSITION_048', 'BS_Ass. Mgr - Admin. & System Support', 48, '{"legacy_sap_code": "BS_Ass. Mgr - Admin. & System Support"}'),
    ('POSITION_049', 'BS_Ass. Mgr - Financial & Special Report', 49, '{"legacy_sap_code": "BS_Ass. Mgr - Financial & Special Report"}'),
    ('POSITION_050', 'BS_Ass. Mgr - Mktg. Planning & Control', 50, '{"legacy_sap_code": "BS_Ass. Mgr - Mktg. Planning & Control"}'),
    ('POSITION_051', 'BS_Ass. Mgr - Technical Parts & Project', 51, '{"legacy_sap_code": "BS_Ass. Mgr - Technical Parts & Project"}'),
    ('POSITION_052', 'BS_Ass.Manager-Accounting & Reports', 52, '{"legacy_sap_code": "BS_Ass.Manager-Accounting & Reports"}'),
    ('POSITION_053', 'BS_Ass.Mgr-Accounts Receivable & Payable', 53, '{"legacy_sap_code": "BS_Ass.Mgr-Accounts Receivable & Payable"}'),
    ('POSITION_054', 'BS_Ass.Mgr-Clearance,Transport&Supplies', 54, '{"legacy_sap_code": "BS_Ass.Mgr-Clearance,Transport&Supplies"}'),
    ('POSITION_055', 'BS_Ass.Mgr-Security & Safety Opt. - Jkt', 55, '{"legacy_sap_code": "BS_Ass.Mgr-Security & Safety Opt. - Jkt"}'),
    ('POSITION_056', 'BS_Assistant Miller - Mill A', 56, '{"legacy_sap_code": "BS_Assistant Miller - Mill A"}'),
    ('POSITION_057', 'BS_Assistant Miller - Mill B', 57, '{"legacy_sap_code": "BS_Assistant Miller - Mill B"}'),
    ('POSITION_058', 'BS_Assistant Miller - Mill C', 58, '{"legacy_sap_code": "BS_Assistant Miller - Mill C"}'),
    ('POSITION_059', 'BS_Assistant Miller - Mill D', 59, '{"legacy_sap_code": "BS_Assistant Miller - Mill D"}'),
    ('POSITION_060', 'BS_Assistant Miller - Mill E', 60, '{"legacy_sap_code": "BS_Assistant Miller - Mill E"}'),
    ('POSITION_061', 'BS_Assistant Miller - Mill F', 61, '{"legacy_sap_code": "BS_Assistant Miller - Mill F"}'),
    ('POSITION_062', 'BS_Assistant Miller - Mill G', 62, '{"legacy_sap_code": "BS_Assistant Miller - Mill G"}'),
    ('POSITION_063', 'BS_Assistant Miller - Mill H', 63, '{"legacy_sap_code": "BS_Assistant Miller - Mill H"}'),
    ('POSITION_064', 'BS_Assistant Miller - Mill I', 64, '{"legacy_sap_code": "BS_Assistant Miller - Mill I"}'),
    ('POSITION_065', 'BS_Assistant Miller - Mill J', 65, '{"legacy_sap_code": "BS_Assistant Miller - Mill J"}'),
    ('POSITION_066', 'BS_Assistant Miller - Mill K', 66, '{"legacy_sap_code": "BS_Assistant Miller - Mill K"}'),
    ('POSITION_067', 'BS_Assistant Miller - Mill L', 67, '{"legacy_sap_code": "BS_Assistant Miller - Mill L"}'),
    ('POSITION_068', 'BS_Assistant Miller - Mill M', 68, '{"legacy_sap_code": "BS_Assistant Miller - Mill M"}'),
    ('POSITION_069', 'BS_Assistant Miller - Mill N', 69, '{"legacy_sap_code": "BS_Assistant Miller - Mill N"}'),
    ('POSITION_070', 'BS_Assistant Miller - Mill O', 70, '{"legacy_sap_code": "BS_Assistant Miller - Mill O"}'),
    ('POSITION_071', 'BS_Asst. Manajer Manufacturing', 71, '{"legacy_sap_code": "BS_Asst. Manajer Manufacturing"}'),
    ('POSITION_072', 'BS_Auditor - Internal Audit 3', 72, '{"legacy_sap_code": "BS_Auditor - Internal Audit 3"}'),
    ('POSITION_073', 'BS_Auditor - Internal Audit Sby', 73, '{"legacy_sap_code": "BS_Auditor - Internal Audit Sby"}'),
    ('POSITION_074', 'BS_CL - Adm Supply', 74, '{"legacy_sap_code": "BS_CL - Adm Supply"}'),
    ('POSITION_075', 'BS_Cashier', 75, '{"legacy_sap_code": "BS_Cashier"}'),
    ('POSITION_076', 'BS_Clerk - Distribution 3', 76, '{"legacy_sap_code": "BS_Clerk - Distribution 3"}'),
    ('POSITION_077', 'BS_Clerk - Distribution 6', 77, '{"legacy_sap_code": "BS_Clerk - Distribution 6"}'),
    ('POSITION_078', 'BS_Clerk - Distribution 7', 78, '{"legacy_sap_code": "BS_Clerk - Distribution 7"}'),
    ('POSITION_079', 'BS_Clerk - Finish Product', 79, '{"legacy_sap_code": "BS_Clerk - Finish Product"}'),
    ('POSITION_080', 'BS_Clerk - Office Service', 80, '{"legacy_sap_code": "BS_Clerk - Office Service"}'),
    ('POSITION_081', 'BS_Clerk - Office Services', 81, '{"legacy_sap_code": "BS_Clerk - Office Services"}'),
    ('POSITION_082', 'BS_Clerk - Production Supplies Stores', 82, '{"legacy_sap_code": "BS_Clerk - Production Supplies Stores"}'),
    ('POSITION_083', 'BS_Clerk - Spare Parts Stores', 83, '{"legacy_sap_code": "BS_Clerk - Spare Parts Stores"}'),
    ('POSITION_084', 'BS_Clerk Office Building', 84, '{"legacy_sap_code": "BS_Clerk Office Building"}'),
    ('POSITION_085', 'BS_Clerk Sales Administration', 85, '{"legacy_sap_code": "BS_Clerk Sales Administration"}'),
    ('POSITION_086', 'BS_Coordinator - Area Sales & Promotion', 86, '{"legacy_sap_code": "BS_Coordinator - Area Sales & Promotion"}'),
    ('POSITION_087', 'BS_Coordinator - Area Sales 1.1.1', 87, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.1.1"}'),
    ('POSITION_088', 'BS_Coordinator - Area Sales 1.1.2', 88, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.1.2"}'),
    ('POSITION_089', 'BS_Coordinator - Area Sales 1.2.1', 89, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.2.1"}'),
    ('POSITION_090', 'BS_Coordinator - Area Sales 1.2.2', 90, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.2.2"}'),
    ('POSITION_091', 'BS_Coordinator - Area Sales 1.3.2', 91, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.3.2"}'),
    ('POSITION_092', 'BS_Coordinator - Area Sales 1.4.1', 92, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.4.1"}'),
    ('POSITION_093', 'BS_Coordinator - Area Sales 1.4.2', 93, '{"legacy_sap_code": "BS_Coordinator - Area Sales 1.4.2"}'),
    ('POSITION_094', 'BS_Coordinator - Area Sales 2.1.1', 94, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.1.1"}'),
    ('POSITION_095', 'BS_Coordinator - Area Sales 2.1.2', 95, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.1.2"}'),
    ('POSITION_096', 'BS_Coordinator - Area Sales 2.2.1', 96, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.2.1"}'),
    ('POSITION_097', 'BS_Coordinator - Area Sales 2.2.2', 97, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.2.2"}'),
    ('POSITION_098', 'BS_Coordinator - Area Sales 2.3.1', 98, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.3.1"}'),
    ('POSITION_099', 'BS_Coordinator - Area Sales 2.3.2', 99, '{"legacy_sap_code": "BS_Coordinator - Area Sales 2.3.2"}'),
    ('POSITION_100', 'BS_Coordinator - Area Sales 3.1.1', 100, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.1.1"}'),
    ('POSITION_101', 'BS_Coordinator - Area Sales 3.1.2', 101, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.1.2"}'),
    ('POSITION_102', 'BS_Coordinator - Area Sales 3.2.1', 102, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.2.1"}'),
    ('POSITION_103', 'BS_Coordinator - Area Sales 3.2.2', 103, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.2.2"}'),
    ('POSITION_104', 'BS_Coordinator - Area Sales 3.2.3', 104, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.2.3"}'),
    ('POSITION_105', 'BS_Coordinator - Area Sales 3.3.1', 105, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.3.1"}'),
    ('POSITION_106', 'BS_Coordinator - Area Sales 3.3.2', 106, '{"legacy_sap_code": "BS_Coordinator - Area Sales 3.3.2"}'),
    ('POSITION_107', 'BS_Drafter', 107, '{"legacy_sap_code": "BS_Drafter"}'),
    ('POSITION_108', 'BS_Drafter - Process Engineering', 108, '{"legacy_sap_code": "BS_Drafter - Process Engineering"}'),
    ('POSITION_109', 'BS_Driver', 109, '{"legacy_sap_code": "BS_Driver"}'),
    ('POSITION_110', 'BS_Dy. Head Miller - Mill Group 1', 110, '{"legacy_sap_code": "BS_Dy. Head Miller - Mill Group 1"}'),
    ('POSITION_111', 'BS_Dy. Head Miller - Mill Group 2', 111, '{"legacy_sap_code": "BS_Dy. Head Miller - Mill Group 2"}'),
    ('POSITION_112', 'BS_Dy. Head Miller - Mill Group 3', 112, '{"legacy_sap_code": "BS_Dy. Head Miller - Mill Group 3"}'),
    ('POSITION_113', 'BS_Dy. Head Miller - Mill Group 4', 113, '{"legacy_sap_code": "BS_Dy. Head Miller - Mill Group 4"}'),
    ('POSITION_114', 'BS_Electrician - Electrical Maintenance', 114, '{"legacy_sap_code": "BS_Electrician - Electrical Maintenance"}'),
    ('POSITION_115', 'BS_Electricians - Workshop', 115, '{"legacy_sap_code": "BS_Electricians - Workshop"}'),
    ('POSITION_116', 'BS_FM-Inspection,Lubrication&Calibration', 116, '{"legacy_sap_code": "BS_FM-Inspection,Lubrication&Calibration"}'),
    ('POSITION_117', 'BS_Foreman - By-Product Packing', 117, '{"legacy_sap_code": "BS_Foreman - By-Product Packing"}'),
    ('POSITION_118', 'BS_Foreman - CP Packing', 118, '{"legacy_sap_code": "BS_Foreman - CP Packing"}'),
    ('POSITION_119', 'BS_Foreman - Carpenter', 119, '{"legacy_sap_code": "BS_Foreman - Carpenter"}'),
    ('POSITION_120', 'BS_Foreman - Compr. , Thermal & Distr. M', 120, '{"legacy_sap_code": "BS_Foreman - Compr. , Thermal & Distr. M"}'),
    ('POSITION_121', 'BS_Foreman - Compressor & Thermal Suppli', 121, '{"legacy_sap_code": "BS_Foreman - Compressor & Thermal Suppli"}'),
    ('POSITION_122', 'BS_Foreman - Consumer Pack Packing', 122, '{"legacy_sap_code": "BS_Foreman - Consumer Pack Packing"}'),
    ('POSITION_123', 'BS_Foreman - Delivery FPS', 123, '{"legacy_sap_code": "BS_Foreman - Delivery FPS"}'),
    ('POSITION_124', 'BS_Foreman - Delivery FPS 2', 124, '{"legacy_sap_code": "BS_Foreman - Delivery FPS 2"}'),
    ('POSITION_125', 'BS_Foreman - Delivery FPS 5', 125, '{"legacy_sap_code": "BS_Foreman - Delivery FPS 5"}'),
    ('POSITION_126', 'BS_Foreman - Delivery FPS 6', 126, '{"legacy_sap_code": "BS_Foreman - Delivery FPS 6"}'),
    ('POSITION_127', 'BS_Foreman - Delivery FPS 7', 127, '{"legacy_sap_code": "BS_Foreman - Delivery FPS 7"}'),
    ('POSITION_128', 'BS_Foreman - Electrical Services', 128, '{"legacy_sap_code": "BS_Foreman - Electrical Services"}'),
    ('POSITION_129', 'BS_Foreman - Fabrication & Fitting', 129, '{"legacy_sap_code": "BS_Foreman - Fabrication & Fitting"}'),
    ('POSITION_130', 'BS_Foreman - Finished Product Stores 1.1', 130, '{"legacy_sap_code": "BS_Foreman - Finished Product Stores 1.1"}'),
    ('POSITION_131', 'BS_Foreman - Finished Product Stores 1.3', 131, '{"legacy_sap_code": "BS_Foreman - Finished Product Stores 1.3"}'),
    ('POSITION_132', 'BS_Foreman - Finished Product Stores 1.4', 132, '{"legacy_sap_code": "BS_Foreman - Finished Product Stores 1.4"}'),
    ('POSITION_133', 'BS_Foreman - Finished Product Stores 3.3', 133, '{"legacy_sap_code": "BS_Foreman - Finished Product Stores 3.3"}'),
    ('POSITION_134', 'BS_Foreman - Flour Bulk & Jumbo', 134, '{"legacy_sap_code": "BS_Foreman - Flour Bulk & Jumbo"}'),
    ('POSITION_135', 'BS_Foreman - Flour Bulk & Jumbo Packing', 135, '{"legacy_sap_code": "BS_Foreman - Flour Bulk & Jumbo Packing"}'),
    ('POSITION_136', 'BS_Foreman - Flour Mixing', 136, '{"legacy_sap_code": "BS_Foreman - Flour Mixing"}'),
    ('POSITION_137', 'BS_Foreman - Flour Packing', 137, '{"legacy_sap_code": "BS_Foreman - Flour Packing"}'),
    ('POSITION_138', 'BS_Foreman - Flour Premium Packing', 138, '{"legacy_sap_code": "BS_Foreman - Flour Premium Packing"}'),
    ('POSITION_139', 'BS_Foreman - Flour Silo', 139, '{"legacy_sap_code": "BS_Foreman - Flour Silo"}'),
    ('POSITION_140', 'BS_Foreman - Garage & Heavy Equipment', 140, '{"legacy_sap_code": "BS_Foreman - Garage & Heavy Equipment"}'),
    ('POSITION_141', 'BS_Foreman - General Material Control', 141, '{"legacy_sap_code": "BS_Foreman - General Material Control"}'),
    ('POSITION_142', 'BS_Foreman - Inventory', 142, '{"legacy_sap_code": "BS_Foreman - Inventory"}'),
    ('POSITION_143', 'BS_Foreman - Jetty Operations', 143, '{"legacy_sap_code": "BS_Foreman - Jetty Operations"}'),
    ('POSITION_144', 'BS_Foreman - LM Jetty A, Pelletizing & P', 144, '{"legacy_sap_code": "BS_Foreman - LM Jetty A, Pelletizing & P"}'),
    ('POSITION_145', 'BS_Foreman - LM Mill - Tangerang', 145, '{"legacy_sap_code": "BS_Foreman - LM Mill - Tangerang"}'),
    ('POSITION_146', 'BS_Foreman - LM Mill DE & KL', 146, '{"legacy_sap_code": "BS_Foreman - LM Mill DE & KL"}'),
    ('POSITION_147', 'BS_Foreman - LM Mill HIJ', 147, '{"legacy_sap_code": "BS_Foreman - LM Mill HIJ"}'),
    ('POSITION_148', 'BS_Foreman - LM Mill MNO', 148, '{"legacy_sap_code": "BS_Foreman - LM Mill MNO"}'),
    ('POSITION_149', 'BS_Foreman - LM Packing FSBP', 149, '{"legacy_sap_code": "BS_Foreman - LM Packing FSBP"}'),
    ('POSITION_150', 'BS_Foreman - LM Wheat Silo AB', 150, '{"legacy_sap_code": "BS_Foreman - LM Wheat Silo AB"}'),
    ('POSITION_151', 'BS_Foreman - Line Maint. Area Packing', 151, '{"legacy_sap_code": "BS_Foreman - Line Maint. Area Packing"}'),
    ('POSITION_152', 'BS_Foreman - Line Maintenance Area Jetty', 152, '{"legacy_sap_code": "BS_Foreman - Line Maintenance Area Jetty"}'),
    ('POSITION_153', 'BS_Foreman - Line Maintenance Area Mills', 153, '{"legacy_sap_code": "BS_Foreman - Line Maintenance Area Mills"}'),
    ('POSITION_154', 'BS_Foreman - Machining & Repair', 154, '{"legacy_sap_code": "BS_Foreman - Machining & Repair"}'),
    ('POSITION_155', 'BS_Foreman - Mechanical Maintenance', 155, '{"legacy_sap_code": "BS_Foreman - Mechanical Maintenance"}'),
    ('POSITION_156', 'BS_Foreman - Mill Support', 156, '{"legacy_sap_code": "BS_Foreman - Mill Support"}'),
    ('POSITION_157', 'BS_Foreman - Pasta Line', 157, '{"legacy_sap_code": "BS_Foreman - Pasta Line"}'),
    ('POSITION_158', 'BS_Foreman - Pasta Packing', 158, '{"legacy_sap_code": "BS_Foreman - Pasta Packing"}'),
    ('POSITION_159', 'BS_Foreman - Pellet Silo', 159, '{"legacy_sap_code": "BS_Foreman - Pellet Silo"}'),
    ('POSITION_160', 'BS_Foreman - Pelletizing', 160, '{"legacy_sap_code": "BS_Foreman - Pelletizing"}'),
    ('POSITION_161', 'BS_Foreman - Pelletizing A', 161, '{"legacy_sap_code": "BS_Foreman - Pelletizing A"}'),
    ('POSITION_162', 'BS_Foreman - Pelletizing B', 162, '{"legacy_sap_code": "BS_Foreman - Pelletizing B"}'),
    ('POSITION_163', 'BS_Foreman - Pest Control', 163, '{"legacy_sap_code": "BS_Foreman - Pest Control"}'),
    ('POSITION_164', 'BS_Foreman - Planning', 164, '{"legacy_sap_code": "BS_Foreman - Planning"}'),
    ('POSITION_165', 'BS_Foreman - Plant Build. & Infrastrct.', 165, '{"legacy_sap_code": "BS_Foreman - Plant Build. & Infrastrct."}'),
    ('POSITION_166', 'BS_Foreman - Power Station Maintenance', 166, '{"legacy_sap_code": "BS_Foreman - Power Station Maintenance"}'),
    ('POSITION_167', 'BS_Foreman - Power Station Operations', 167, '{"legacy_sap_code": "BS_Foreman - Power Station Operations"}'),
    ('POSITION_168', 'BS_Foreman - Production FPS', 168, '{"legacy_sap_code": "BS_Foreman - Production FPS"}'),
    ('POSITION_169', 'BS_Foreman - Production FPS 1', 169, '{"legacy_sap_code": "BS_Foreman - Production FPS 1"}'),
    ('POSITION_170', 'BS_Foreman - Production FPS 3', 170, '{"legacy_sap_code": "BS_Foreman - Production FPS 3"}'),
    ('POSITION_171', 'BS_Foreman - Production FPS 5', 171, '{"legacy_sap_code": "BS_Foreman - Production FPS 5"}'),
    ('POSITION_172', 'BS_Foreman - Production FPS 6', 172, '{"legacy_sap_code": "BS_Foreman - Production FPS 6"}'),
    ('POSITION_173', 'BS_Foreman - Production FPS 7', 173, '{"legacy_sap_code": "BS_Foreman - Production FPS 7"}'),
    ('POSITION_174', 'BS_Foreman - QC', 174, '{"legacy_sap_code": "BS_Foreman - QC"}'),
    ('POSITION_175', 'BS_Foreman - Roll Mill', 175, '{"legacy_sap_code": "BS_Foreman - Roll Mill"}'),
    ('POSITION_176', 'BS_Foreman - Security & Fire Brigade', 176, '{"legacy_sap_code": "BS_Foreman - Security & Fire Brigade"}'),
    ('POSITION_177', 'BS_Foreman - Security - Tgr', 177, '{"legacy_sap_code": "BS_Foreman - Security - Tgr"}'),
    ('POSITION_178', 'BS_Foreman - Security Area 1.2.1', 178, '{"legacy_sap_code": "BS_Foreman - Security Area 1.2.1"}'),
    ('POSITION_179', 'BS_Foreman - Security Area 1.4.1', 179, '{"legacy_sap_code": "BS_Foreman - Security Area 1.4.1"}'),
    ('POSITION_180', 'BS_Foreman - Semolina Inventory Control', 180, '{"legacy_sap_code": "BS_Foreman - Semolina Inventory Control"}'),
    ('POSITION_181', 'BS_Foreman - Shift A Maint. FMP & FSBP', 181, '{"legacy_sap_code": "BS_Foreman - Shift A Maint. FMP & FSBP"}'),
    ('POSITION_182', 'BS_Foreman - Shift A Maintenance Jetty &', 182, '{"legacy_sap_code": "BS_Foreman - Shift A Maintenance Jetty &"}'),
    ('POSITION_183', 'BS_Foreman - Shift B Maint. FMP & FSBP', 183, '{"legacy_sap_code": "BS_Foreman - Shift B Maint. FMP & FSBP"}'),
    ('POSITION_184', 'BS_Foreman - Shift B Maintenance Jetty &', 184, '{"legacy_sap_code": "BS_Foreman - Shift B Maintenance Jetty &"}'),
    ('POSITION_185', 'BS_Foreman - Shift C Maint. FMP & FSBP', 185, '{"legacy_sap_code": "BS_Foreman - Shift C Maint. FMP & FSBP"}'),
    ('POSITION_186', 'BS_Foreman - Shift CK Maint. Mill', 186, '{"legacy_sap_code": "BS_Foreman - Shift CK Maint. Mill"}'),
    ('POSITION_187', 'BS_Foreman - Shift KB Maint. Mill', 187, '{"legacy_sap_code": "BS_Foreman - Shift KB Maint. Mill"}'),
    ('POSITION_188', 'BS_Foreman - Shift SB Maint. Mill', 188, '{"legacy_sap_code": "BS_Foreman - Shift SB Maint. Mill"}'),
    ('POSITION_189', 'BS_Foreman - Storage Delivery', 189, '{"legacy_sap_code": "BS_Foreman - Storage Delivery"}'),
    ('POSITION_190', 'BS_Foreman - Storage Production', 190, '{"legacy_sap_code": "BS_Foreman - Storage Production"}'),
    ('POSITION_191', 'BS_Foreman - Storage Support', 191, '{"legacy_sap_code": "BS_Foreman - Storage Support"}'),
    ('POSITION_192', 'BS_Foreman - Thermal', 192, '{"legacy_sap_code": "BS_Foreman - Thermal"}'),
    ('POSITION_193', 'BS_Foreman - Waste Management', 193, '{"legacy_sap_code": "BS_Foreman - Waste Management"}'),
    ('POSITION_194', 'BS_Foreman - Water & Distribution Mainte', 194, '{"legacy_sap_code": "BS_Foreman - Water & Distribution Mainte"}'),
    ('POSITION_195', 'BS_Foreman - Water Facility', 195, '{"legacy_sap_code": "BS_Foreman - Water Facility"}'),
    ('POSITION_196', 'BS_Foreman - Water Supplies', 196, '{"legacy_sap_code": "BS_Foreman - Water Supplies"}'),
    ('POSITION_197', 'BS_Foreman - Wheat Silo', 197, '{"legacy_sap_code": "BS_Foreman - Wheat Silo"}'),
    ('POSITION_198', 'BS_Foreman - Wheat Silo A', 198, '{"legacy_sap_code": "BS_Foreman - Wheat Silo A"}'),
    ('POSITION_199', 'BS_Foreman - Wheat Silo B', 199, '{"legacy_sap_code": "BS_Foreman - Wheat Silo B"}'),
    ('POSITION_200', 'BS_Foreman -Fluting Services', 200, '{"legacy_sap_code": "BS_Foreman -Fluting Services"}'),
    ('POSITION_201', 'BS_Foreman-Flour Packg & Supp Material', 201, '{"legacy_sap_code": "BS_Foreman-Flour Packg & Supp Material"}'),
    ('POSITION_202', 'BS_Guard - Security & Fire Brigade', 202, '{"legacy_sap_code": "BS_Guard - Security & Fire Brigade"}'),
    ('POSITION_203', 'BS_Guard - Security 1.1', 203, '{"legacy_sap_code": "BS_Guard - Security 1.1"}'),
    ('POSITION_204', 'BS_Guard - Security 1.2', 204, '{"legacy_sap_code": "BS_Guard - Security 1.2"}'),
    ('POSITION_205', 'BS_Head - Public Relations', 205, '{"legacy_sap_code": "BS_Head - Public Relations"}'),
    ('POSITION_206', 'BS_Head Miller - Mill Group 2', 206, '{"legacy_sap_code": "BS_Head Miller - Mill Group 2"}'),
    ('POSITION_207', 'BS_Head Miller - Mill Group 3', 207, '{"legacy_sap_code": "BS_Head Miller - Mill Group 3"}'),
    ('POSITION_208', 'BS_Head Miller - Mill Group 4', 208, '{"legacy_sap_code": "BS_Head Miller - Mill Group 4"}'),
    ('POSITION_209', 'BS_Helper - BBC 3.2.1', 209, '{"legacy_sap_code": "BS_Helper - BBC 3.2.1"}'),
    ('POSITION_210', 'BS_Inspector - Finished Goods', 210, '{"legacy_sap_code": "BS_Inspector - Finished Goods"}'),
    ('POSITION_211', 'BS_Inspector - Safety Operations', 211, '{"legacy_sap_code": "BS_Inspector - Safety Operations"}'),
    ('POSITION_212', 'BS_Inspectors - QA, Hygiene, Safety', 212, '{"legacy_sap_code": "BS_Inspectors - QA, Hygiene, Safety"}'),
    ('POSITION_213', 'BS_Inspectors - Quality Assurance - Sby', 213, '{"legacy_sap_code": "BS_Inspectors - Quality Assurance - Sby"}'),
    ('POSITION_214', 'BS_Inspectors - Safety Operations', 214, '{"legacy_sap_code": "BS_Inspectors - Safety Operations"}'),
    ('POSITION_215', 'BS_Instructor - BBC Area 2.3.2', 215, '{"legacy_sap_code": "BS_Instructor - BBC Area 2.3.2"}'),
    ('POSITION_216', 'BS_Instructor - BBC Area 3.1.3', 216, '{"legacy_sap_code": "BS_Instructor - BBC Area 3.1.3"}'),
    ('POSITION_217', 'BS_Instructor - BBC Area 3.2.1', 217, '{"legacy_sap_code": "BS_Instructor - BBC Area 3.2.1"}'),
    ('POSITION_218', 'BS_Jr. Manager - Human Resources', 218, '{"legacy_sap_code": "BS_Jr. Manager - Human Resources"}'),
    ('POSITION_219', 'BS_Jr. Manager - Instrument &Calibration', 219, '{"legacy_sap_code": "BS_Jr. Manager - Instrument &Calibration"}'),
    ('POSITION_220', 'BS_Jr. Manager - LM Mill Area 1', 220, '{"legacy_sap_code": "BS_Jr. Manager - LM Mill Area 1"}'),
    ('POSITION_221', 'BS_Jr. Manager - LM Mill Area 2', 221, '{"legacy_sap_code": "BS_Jr. Manager - LM Mill Area 2"}'),
    ('POSITION_222', 'BS_Jr. Manager - LM Packing FMP', 222, '{"legacy_sap_code": "BS_Jr. Manager - LM Packing FMP"}'),
    ('POSITION_223', 'BS_Jr. Manager - LM Packing FSBP', 223, '{"legacy_sap_code": "BS_Jr. Manager - LM Packing FSBP"}'),
    ('POSITION_224', 'BS_Jr. Manager - Marketing Service', 224, '{"legacy_sap_code": "BS_Jr. Manager - Marketing Service"}'),
    ('POSITION_225', 'BS_Jr. Manager - PPIC', 225, '{"legacy_sap_code": "BS_Jr. Manager - PPIC"}'),
    ('POSITION_226', 'BS_Jr. Manager - Plant Ctrl.&Syst. Digit', 226, '{"legacy_sap_code": "BS_Jr. Manager - Plant Ctrl.&Syst. Digit"}'),
    ('POSITION_227', 'BS_Jr. Manager - Process Planning & Eng.', 227, '{"legacy_sap_code": "BS_Jr. Manager - Process Planning & Eng."}'),
    ('POSITION_228', 'BS_Jr. Manager - Tech. Planning & Eng.', 228, '{"legacy_sap_code": "BS_Jr. Manager - Tech. Planning & Eng."}'),
    ('POSITION_229', 'BS_Jr. Manager-LM Mill Area 3', 229, '{"legacy_sap_code": "BS_Jr. Manager-LM Mill Area 3"}'),
    ('POSITION_230', 'BS_Jr. Mgr-Production Supply & Waste Mgt', 230, '{"legacy_sap_code": "BS_Jr. Mgr-Production Supply & Waste Mgt"}'),
    ('POSITION_231', 'BS_Jr. Mgr-Quality & Product Development', 231, '{"legacy_sap_code": "BS_Jr. Mgr-Quality & Product Development"}'),
    ('POSITION_232', 'BS_Jr. Secretary - Area Sales 3', 232, '{"legacy_sap_code": "BS_Jr. Secretary - Area Sales 3"}'),
    ('POSITION_233', 'BS_Jr. Specialist - End Product/Baker', 233, '{"legacy_sap_code": "BS_Jr. Specialist - End Product/Baker"}'),
    ('POSITION_234', 'BS_Jr. Specialist - Networking & Digital', 234, '{"legacy_sap_code": "BS_Jr. Specialist - Networking & Digital"}'),
    ('POSITION_235', 'BS_Jr. Specialist - Plant Control System', 235, '{"legacy_sap_code": "BS_Jr. Specialist - Plant Control System"}'),
    ('POSITION_236', 'BS_Jr. Specialist - Research & Developme', 236, '{"legacy_sap_code": "BS_Jr. Specialist - Research & Developme"}'),
    ('POSITION_237', 'BS_Jr.Manager - Compressor & Thermal', 237, '{"legacy_sap_code": "BS_Jr.Manager - Compressor & Thermal"}'),
    ('POSITION_238', 'BS_Jr.Manager-Technical General Support', 238, '{"legacy_sap_code": "BS_Jr.Manager-Technical General Support"}'),
    ('POSITION_239', 'BS_Jr.Staff-Outsource Mgmt&Factory Clean', 239, '{"legacy_sap_code": "BS_Jr.Staff-Outsource Mgmt&Factory Clean"}'),
    ('POSITION_240', 'BS_Kerani 1.1', 240, '{"legacy_sap_code": "BS_Kerani 1.1"}'),
    ('POSITION_241', 'BS_Kerani 1.4.1', 241, '{"legacy_sap_code": "BS_Kerani 1.4.1"}'),
    ('POSITION_242', 'BS_Kerani 3.3.2', 242, '{"legacy_sap_code": "BS_Kerani 3.3.2"}'),
    ('POSITION_243', 'BS_Line Inspectors - QC', 243, '{"legacy_sap_code": "BS_Line Inspectors - QC"}'),
    ('POSITION_244', 'BS_Manager - Accounting & Financial Plan', 244, '{"legacy_sap_code": "BS_Manager - Accounting & Financial Plan"}'),
    ('POSITION_245', 'BS_Manager - Accounting & Tax', 245, '{"legacy_sap_code": "BS_Manager - Accounting & Tax"}'),
    ('POSITION_246', 'BS_Manager - Area Sales 1.1', 246, '{"legacy_sap_code": "BS_Manager - Area Sales 1.1"}'),
    ('POSITION_247', 'BS_Manager - Area Sales 1.4', 247, '{"legacy_sap_code": "BS_Manager - Area Sales 1.4"}'),
    ('POSITION_248', 'BS_Manager - Area Sales 2.1', 248, '{"legacy_sap_code": "BS_Manager - Area Sales 2.1"}'),
    ('POSITION_249', 'BS_Manager - Credit, Billing & Collectio', 249, '{"legacy_sap_code": "BS_Manager - Credit, Billing & Collectio"}'),
    ('POSITION_250', 'BS_Manager - Eastern Area Direct Sales', 250, '{"legacy_sap_code": "BS_Manager - Eastern Area Direct Sales"}'),
    ('POSITION_251', 'BS_Manager - Flour Export & By-Product S', 251, '{"legacy_sap_code": "BS_Manager - Flour Export & By-Product S"}'),
    ('POSITION_252', 'BS_Manager - Gen. Accounting & Financial', 252, '{"legacy_sap_code": "BS_Manager - Gen. Accounting & Financial"}'),
    ('POSITION_253', 'BS_Manager - HRGA Operations - Jkt', 253, '{"legacy_sap_code": "BS_Manager - HRGA Operations - Jkt"}'),
    ('POSITION_254', 'BS_Manager - Jetty & Silo', 254, '{"legacy_sap_code": "BS_Manager - Jetty & Silo"}'),
    ('POSITION_255', 'BS_Manager - Legal & License', 255, '{"legacy_sap_code": "BS_Manager - Legal & License"}'),
    ('POSITION_256', 'BS_Manager - Line Maintenance Mill I, II', 256, '{"legacy_sap_code": "BS_Manager - Line Maintenance Mill I, II"}'),
    ('POSITION_257', 'BS_Manager - Line Maintenance Packing', 257, '{"legacy_sap_code": "BS_Manager - Line Maintenance Packing"}'),
    ('POSITION_258', 'BS_Manager - Marketing', 258, '{"legacy_sap_code": "BS_Manager - Marketing"}'),
    ('POSITION_259', 'BS_Manager - Non-Technical Items', 259, '{"legacy_sap_code": "BS_Manager - Non-Technical Items"}'),
    ('POSITION_260', 'BS_Manager - Operations - Tgr', 260, '{"legacy_sap_code": "BS_Manager - Operations - Tgr"}'),
    ('POSITION_261', 'BS_Manager - PQC', 261, '{"legacy_sap_code": "BS_Manager - PQC"}'),
    ('POSITION_262', 'BS_Manager - People & Organization Dev.', 262, '{"legacy_sap_code": "BS_Manager - People & Organization Dev."}'),
    ('POSITION_263', 'BS_Manager - Production Planning & Inven', 263, '{"legacy_sap_code": "BS_Manager - Production Planning & Inven"}'),
    ('POSITION_264', 'BS_Manager - Production Utility', 264, '{"legacy_sap_code": "BS_Manager - Production Utility"}'),
    ('POSITION_265', 'BS_Manager - Project & Dev. Engineering', 265, '{"legacy_sap_code": "BS_Manager - Project & Dev. Engineering"}'),
    ('POSITION_266', 'BS_Manager - Purchasing - Sby', 266, '{"legacy_sap_code": "BS_Manager - Purchasing - Sby"}'),
    ('POSITION_267', 'BS_Manager - QA', 267, '{"legacy_sap_code": "BS_Manager - QA"}'),
    ('POSITION_268', 'BS_Manager - Report & Analyses', 268, '{"legacy_sap_code": "BS_Manager - Report & Analyses"}'),
    ('POSITION_269', 'BS_Manager - Reporting & Business Planni', 269, '{"legacy_sap_code": "BS_Manager - Reporting & Business Planni"}'),
    ('POSITION_270', 'BS_Manager - SME & BBC Development', 270, '{"legacy_sap_code": "BS_Manager - SME & BBC Development"}'),
    ('POSITION_271', 'BS_Manager-Automation & Syst Digital', 271, '{"legacy_sap_code": "BS_Manager-Automation & Syst Digital"}'),
    ('POSITION_272', 'BS_Manager-Flour Silo, Mixing & Packing', 272, '{"legacy_sap_code": "BS_Manager-Flour Silo, Mixing & Packing"}'),
    ('POSITION_273', 'BS_Manager-Line Maint. Jetty & Silo', 273, '{"legacy_sap_code": "BS_Manager-Line Maint. Jetty & Silo"}'),
    ('POSITION_274', 'BS_Manager-Material & Waste Management', 274, '{"legacy_sap_code": "BS_Manager-Material & Waste Management"}'),
    ('POSITION_275', 'BS_Manager-Workshop & Plant Infrastructu', 275, '{"legacy_sap_code": "BS_Manager-Workshop & Plant Infrastructu"}'),
    ('POSITION_276', 'BS_Mechanic - Mechanical Maintenance', 276, '{"legacy_sap_code": "BS_Mechanic - Mechanical Maintenance"}'),
    ('POSITION_277', 'BS_Mechanics - Garage', 277, '{"legacy_sap_code": "BS_Mechanics - Garage"}'),
    ('POSITION_278', 'BS_Mechanics - Machining & Repair', 278, '{"legacy_sap_code": "BS_Mechanics - Machining & Repair"}'),
    ('POSITION_279', 'BS_Messenger', 279, '{"legacy_sap_code": "BS_Messenger"}'),
    ('POSITION_280', 'BS_Mgr-National Consumer Branded Product', 280, '{"legacy_sap_code": "BS_Mgr-National Consumer Branded Product"}'),
    ('POSITION_281', 'BS_Miller - Mill A', 281, '{"legacy_sap_code": "BS_Miller - Mill A"}'),
    ('POSITION_282', 'BS_Miller - Mill B', 282, '{"legacy_sap_code": "BS_Miller - Mill B"}'),
    ('POSITION_283', 'BS_Miller - Mill C', 283, '{"legacy_sap_code": "BS_Miller - Mill C"}'),
    ('POSITION_284', 'BS_Miller - Mill CA', 284, '{"legacy_sap_code": "BS_Miller - Mill CA"}'),
    ('POSITION_285', 'BS_Miller - Mill CC', 285, '{"legacy_sap_code": "BS_Miller - Mill CC"}'),
    ('POSITION_286', 'BS_Miller - Mill D', 286, '{"legacy_sap_code": "BS_Miller - Mill D"}'),
    ('POSITION_287', 'BS_Miller - Mill E', 287, '{"legacy_sap_code": "BS_Miller - Mill E"}'),
    ('POSITION_288', 'BS_Miller - Mill F', 288, '{"legacy_sap_code": "BS_Miller - Mill F"}'),
    ('POSITION_289', 'BS_Miller - Mill G', 289, '{"legacy_sap_code": "BS_Miller - Mill G"}'),
    ('POSITION_290', 'BS_Miller - Mill H', 290, '{"legacy_sap_code": "BS_Miller - Mill H"}'),
    ('POSITION_291', 'BS_Miller - Mill I', 291, '{"legacy_sap_code": "BS_Miller - Mill I"}'),
    ('POSITION_292', 'BS_Miller - Mill J', 292, '{"legacy_sap_code": "BS_Miller - Mill J"}'),
    ('POSITION_293', 'BS_Miller - Mill K', 293, '{"legacy_sap_code": "BS_Miller - Mill K"}'),
    ('POSITION_294', 'BS_Miller - Mill M', 294, '{"legacy_sap_code": "BS_Miller - Mill M"}'),
    ('POSITION_295', 'BS_Miller - Mill N', 295, '{"legacy_sap_code": "BS_Miller - Mill N"}'),
    ('POSITION_296', 'BS_Miller - Mill O', 296, '{"legacy_sap_code": "BS_Miller - Mill O"}'),
    ('POSITION_297', 'BS_OP-QC Laminating + Extruder + Conv.', 297, '{"legacy_sap_code": "BS_OP-QC Laminating + Extruder + Conv."}'),
    ('POSITION_298', 'BS_Office Boy', 298, '{"legacy_sap_code": "BS_Office Boy"}'),
    ('POSITION_299', 'BS_Officer - Accounts Payable', 299, '{"legacy_sap_code": "BS_Officer - Accounts Payable"}'),
    ('POSITION_300', 'BS_Officer - Canteen', 300, '{"legacy_sap_code": "BS_Officer - Canteen"}'),
    ('POSITION_301', 'BS_Officer - Credit, Billing & Collectio', 301, '{"legacy_sap_code": "BS_Officer - Credit, Billing & Collectio"}'),
    ('POSITION_302', 'BS_Officer - Disbursement', 302, '{"legacy_sap_code": "BS_Officer - Disbursement"}'),
    ('POSITION_303', 'BS_Officer - Distribution', 303, '{"legacy_sap_code": "BS_Officer - Distribution"}'),
    ('POSITION_304', 'BS_Officer - Distribution 1', 304, '{"legacy_sap_code": "BS_Officer - Distribution 1"}'),
    ('POSITION_305', 'BS_Officer - Distribution 2', 305, '{"legacy_sap_code": "BS_Officer - Distribution 2"}'),
    ('POSITION_306', 'BS_Officer - Distribution 4', 306, '{"legacy_sap_code": "BS_Officer - Distribution 4"}'),
    ('POSITION_307', 'BS_Officer - Gate Office - Sby 2', 307, '{"legacy_sap_code": "BS_Officer - Gate Office - Sby 2"}'),
    ('POSITION_308', 'BS_Officer - Gate Office - Sby 3', 308, '{"legacy_sap_code": "BS_Officer - Gate Office - Sby 3"}'),
    ('POSITION_309', 'BS_Officer - General Ledger 2', 309, '{"legacy_sap_code": "BS_Officer - General Ledger 2"}'),
    ('POSITION_310', 'BS_Officer - Payment Executor 1', 310, '{"legacy_sap_code": "BS_Officer - Payment Executor 1"}'),
    ('POSITION_311', 'BS_Officer - Public Relations', 311, '{"legacy_sap_code": "BS_Officer - Public Relations"}'),
    ('POSITION_312', 'BS_Officer - Sales Admin. - Sby', 312, '{"legacy_sap_code": "BS_Officer - Sales Admin. - Sby"}'),
    ('POSITION_313', 'BS_Officer - Sales Admin. - Sby 2', 313, '{"legacy_sap_code": "BS_Officer - Sales Admin. - Sby 2"}'),
    ('POSITION_314', 'BS_Officer - Transport. & Courier Serv.', 314, '{"legacy_sap_code": "BS_Officer - Transport. & Courier Serv."}'),
    ('POSITION_315', 'BS_Officer-Credit,Billing&Collection Adm', 315, '{"legacy_sap_code": "BS_Officer-Credit,Billing&Collection Adm"}'),
    ('POSITION_316', 'BS_Officer-Housekeeping &Office Cleaning', 316, '{"legacy_sap_code": "BS_Officer-Housekeeping &Office Cleaning"}'),
    ('POSITION_317', 'BS_Officer-Transport. & Courier Services', 317, '{"legacy_sap_code": "BS_Officer-Transport. & Courier Services"}'),
    ('POSITION_318', 'BS_Op -  RtR Printing', 318, '{"legacy_sap_code": "BS_Op -  RtR Printing"}'),
    ('POSITION_319', 'BS_Op - Circular', 319, '{"legacy_sap_code": "BS_Op - Circular"}'),
    ('POSITION_320', 'BS_Op - Circular CS', 320, '{"legacy_sap_code": "BS_Op - Circular CS"}'),
    ('POSITION_321', 'BS_Op - Circular Jumbo', 321, '{"legacy_sap_code": "BS_Op - Circular Jumbo"}'),
    ('POSITION_322', 'BS_Op - Circular Phls A', 322, '{"legacy_sap_code": "BS_Op - Circular Phls A"}'),
    ('POSITION_323', 'BS_Op - Circular STA', 323, '{"legacy_sap_code": "BS_Op - Circular STA"}'),
    ('POSITION_324', 'BS_Op - Circular YM B', 324, '{"legacy_sap_code": "BS_Op - Circular YM B"}'),
    ('POSITION_325', 'BS_Op - Circular YM C', 325, '{"legacy_sap_code": "BS_Op - Circular YM C"}'),
    ('POSITION_326', 'BS_Op - Circular YM D', 326, '{"legacy_sap_code": "BS_Op - Circular YM D"}'),
    ('POSITION_327', 'BS_Op - Clerk Adm Circular', 327, '{"legacy_sap_code": "BS_Op - Clerk Adm Circular"}'),
    ('POSITION_328', 'BS_Op - Conv - Ct - Sew - Auto', 328, '{"legacy_sap_code": "BS_Op - Conv - Ct - Sew - Auto"}'),
    ('POSITION_329', 'BS_Op - Laminating', 329, '{"legacy_sap_code": "BS_Op - Laminating"}'),
    ('POSITION_330', 'BS_Op / Store Keeper Waste', 330, '{"legacy_sap_code": "BS_Op / Store Keeper Waste"}'),
    ('POSITION_331', 'BS_Operator - By-Product Packing', 331, '{"legacy_sap_code": "BS_Operator - By-Product Packing"}'),
    ('POSITION_332', 'BS_Operator - Circular', 332, '{"legacy_sap_code": "BS_Operator - Circular"}'),
    ('POSITION_333', 'BS_Operator - Circular Jumbo', 333, '{"legacy_sap_code": "BS_Operator - Circular Jumbo"}'),
    ('POSITION_334', 'BS_Operator - Circular Nova A', 334, '{"legacy_sap_code": "BS_Operator - Circular Nova A"}'),
    ('POSITION_335', 'BS_Operator - Circular Nova B', 335, '{"legacy_sap_code": "BS_Operator - Circular Nova B"}'),
    ('POSITION_336', 'BS_Operator - Circular Omega A', 336, '{"legacy_sap_code": "BS_Operator - Circular Omega A"}'),
    ('POSITION_337', 'BS_Operator - Consumer Pack Packing', 337, '{"legacy_sap_code": "BS_Operator - Consumer Pack Packing"}'),
    ('POSITION_338', 'BS_Operator - Converting', 338, '{"legacy_sap_code": "BS_Operator - Converting"}'),
    ('POSITION_339', 'BS_Operator - Converting Remflex', 339, '{"legacy_sap_code": "BS_Operator - Converting Remflex"}'),
    ('POSITION_340', 'BS_Operator - Delivery FPS 11', 340, '{"legacy_sap_code": "BS_Operator - Delivery FPS 11"}'),
    ('POSITION_341', 'BS_Operator - Delivery FPS 17', 341, '{"legacy_sap_code": "BS_Operator - Delivery FPS 17"}'),
    ('POSITION_342', 'BS_Operator - Delivery FPS 19', 342, '{"legacy_sap_code": "BS_Operator - Delivery FPS 19"}'),
    ('POSITION_343', 'BS_Operator - Delivery FPS 22', 343, '{"legacy_sap_code": "BS_Operator - Delivery FPS 22"}'),
    ('POSITION_344', 'BS_Operator - Delivery FPS 4', 344, '{"legacy_sap_code": "BS_Operator - Delivery FPS 4"}'),
    ('POSITION_345', 'BS_Operator - Delivery FPS 5', 345, '{"legacy_sap_code": "BS_Operator - Delivery FPS 5"}'),
    ('POSITION_346', 'BS_Operator - Delivery FPS 7', 346, '{"legacy_sap_code": "BS_Operator - Delivery FPS 7"}'),
    ('POSITION_347', 'BS_Operator - Deposit Material', 347, '{"legacy_sap_code": "BS_Operator - Deposit Material"}'),
    ('POSITION_348', 'BS_Operator - Fabrication & Fitting', 348, '{"legacy_sap_code": "BS_Operator - Fabrication & Fitting"}'),
    ('POSITION_349', 'BS_Operator - Finished Product Inventory', 349, '{"legacy_sap_code": "BS_Operator - Finished Product Inventory"}'),
    ('POSITION_350', 'BS_Operator - Flour Bulk & Jumbo', 350, '{"legacy_sap_code": "BS_Operator - Flour Bulk & Jumbo"}'),
    ('POSITION_351', 'BS_Operator - Flour Bulk & Jumbo Packing', 351, '{"legacy_sap_code": "BS_Operator - Flour Bulk & Jumbo Packing"}'),
    ('POSITION_352', 'BS_Operator - Flour Mixing', 352, '{"legacy_sap_code": "BS_Operator - Flour Mixing"}'),
    ('POSITION_353', 'BS_Operator - Flour Mixing & Packing', 353, '{"legacy_sap_code": "BS_Operator - Flour Mixing & Packing"}'),
    ('POSITION_354', 'BS_Operator - Flour Packing', 354, '{"legacy_sap_code": "BS_Operator - Flour Packing"}'),
    ('POSITION_355', 'BS_Operator - Flour Silo', 355, '{"legacy_sap_code": "BS_Operator - Flour Silo"}'),
    ('POSITION_356', 'BS_Operator - Forklift', 356, '{"legacy_sap_code": "BS_Operator - Forklift"}'),
    ('POSITION_357', 'BS_Operator - Forklift - Tgr', 357, '{"legacy_sap_code": "BS_Operator - Forklift - Tgr"}'),
    ('POSITION_358', 'BS_Operator - Forklift 1', 358, '{"legacy_sap_code": "BS_Operator - Forklift 1"}'),
    ('POSITION_359', 'BS_Operator - Forklift 1.4.1', 359, '{"legacy_sap_code": "BS_Operator - Forklift 1.4.1"}'),
    ('POSITION_360', 'BS_Operator - Forklift 35', 360, '{"legacy_sap_code": "BS_Operator - Forklift 35"}'),
    ('POSITION_361', 'BS_Operator - Forklift 42', 361, '{"legacy_sap_code": "BS_Operator - Forklift 42"}'),
    ('POSITION_362', 'BS_Operator - General Facility', 362, '{"legacy_sap_code": "BS_Operator - General Facility"}'),
    ('POSITION_363', 'BS_Operator - Inventory', 363, '{"legacy_sap_code": "BS_Operator - Inventory"}'),
    ('POSITION_364', 'BS_Operator - Jetty', 364, '{"legacy_sap_code": "BS_Operator - Jetty"}'),
    ('POSITION_365', 'BS_Operator - Jumbo', 365, '{"legacy_sap_code": "BS_Operator - Jumbo"}'),
    ('POSITION_366', 'BS_Operator - Laminating', 366, '{"legacy_sap_code": "BS_Operator - Laminating"}'),
    ('POSITION_367', 'BS_Operator - Line Maintenance Area Jett', 367, '{"legacy_sap_code": "BS_Operator - Line Maintenance Area Jett"}'),
    ('POSITION_368', 'BS_Operator - Line Maintenance Area Mill', 368, '{"legacy_sap_code": "BS_Operator - Line Maintenance Area Mill"}'),
    ('POSITION_369', 'BS_Operator - Line Maintenance Area Pack', 369, '{"legacy_sap_code": "BS_Operator - Line Maintenance Area Pack"}'),
    ('POSITION_370', 'BS_Operator - Mill A', 370, '{"legacy_sap_code": "BS_Operator - Mill A"}'),
    ('POSITION_371', 'BS_Operator - Mill B', 371, '{"legacy_sap_code": "BS_Operator - Mill B"}'),
    ('POSITION_372', 'BS_Operator - Mill D', 372, '{"legacy_sap_code": "BS_Operator - Mill D"}'),
    ('POSITION_373', 'BS_Operator - Mill E', 373, '{"legacy_sap_code": "BS_Operator - Mill E"}'),
    ('POSITION_374', 'BS_Operator - Mill F', 374, '{"legacy_sap_code": "BS_Operator - Mill F"}'),
    ('POSITION_375', 'BS_Operator - Mill G', 375, '{"legacy_sap_code": "BS_Operator - Mill G"}'),
    ('POSITION_376', 'BS_Operator - Mill H', 376, '{"legacy_sap_code": "BS_Operator - Mill H"}'),
    ('POSITION_377', 'BS_Operator - Mill I', 377, '{"legacy_sap_code": "BS_Operator - Mill I"}'),
    ('POSITION_378', 'BS_Operator - Mill J', 378, '{"legacy_sap_code": "BS_Operator - Mill J"}'),
    ('POSITION_379', 'BS_Operator - Mill K', 379, '{"legacy_sap_code": "BS_Operator - Mill K"}'),
    ('POSITION_380', 'BS_Operator - Mill L', 380, '{"legacy_sap_code": "BS_Operator - Mill L"}'),
    ('POSITION_381', 'BS_Operator - Mill M', 381, '{"legacy_sap_code": "BS_Operator - Mill M"}'),
    ('POSITION_382', 'BS_Operator - Mill N', 382, '{"legacy_sap_code": "BS_Operator - Mill N"}'),
    ('POSITION_383', 'BS_Operator - Mill O', 383, '{"legacy_sap_code": "BS_Operator - Mill O"}'),
    ('POSITION_384', 'BS_Operator - Mill Support', 384, '{"legacy_sap_code": "BS_Operator - Mill Support"}'),
    ('POSITION_385', 'BS_Operator - PQC Sby', 385, '{"legacy_sap_code": "BS_Operator - PQC Sby"}'),
    ('POSITION_386', 'BS_Operator - Pasta Line', 386, '{"legacy_sap_code": "BS_Operator - Pasta Line"}'),
    ('POSITION_387', 'BS_Operator - Pasta Manual Packing', 387, '{"legacy_sap_code": "BS_Operator - Pasta Manual Packing"}'),
    ('POSITION_388', 'BS_Operator - Pasta Packing', 388, '{"legacy_sap_code": "BS_Operator - Pasta Packing"}'),
    ('POSITION_389', 'BS_Operator - Pasta Packing Machine', 389, '{"legacy_sap_code": "BS_Operator - Pasta Packing Machine"}'),
    ('POSITION_390', 'BS_Operator - Pellet Silo', 390, '{"legacy_sap_code": "BS_Operator - Pellet Silo"}'),
    ('POSITION_391', 'BS_Operator - Pelletizing', 391, '{"legacy_sap_code": "BS_Operator - Pelletizing"}'),
    ('POSITION_392', 'BS_Operator - Pest Control', 392, '{"legacy_sap_code": "BS_Operator - Pest Control"}'),
    ('POSITION_393', 'BS_Operator - Power Station Maintenance', 393, '{"legacy_sap_code": "BS_Operator - Power Station Maintenance"}'),
    ('POSITION_394', 'BS_Operator - Power Station Operations', 394, '{"legacy_sap_code": "BS_Operator - Power Station Operations"}'),
    ('POSITION_395', 'BS_Operator - Production FPS 1', 395, '{"legacy_sap_code": "BS_Operator - Production FPS 1"}'),
    ('POSITION_396', 'BS_Operator - Production FPS 10', 396, '{"legacy_sap_code": "BS_Operator - Production FPS 10"}'),
    ('POSITION_397', 'BS_Operator - Production FPS 15', 397, '{"legacy_sap_code": "BS_Operator - Production FPS 15"}'),
    ('POSITION_398', 'BS_Operator - Production FPS 16', 398, '{"legacy_sap_code": "BS_Operator - Production FPS 16"}'),
    ('POSITION_399', 'BS_Operator - Production FPS 18', 399, '{"legacy_sap_code": "BS_Operator - Production FPS 18"}'),
    ('POSITION_400', 'BS_Operator - Production FPS 2', 400, '{"legacy_sap_code": "BS_Operator - Production FPS 2"}'),
    ('POSITION_401', 'BS_Operator - Production FPS 3', 401, '{"legacy_sap_code": "BS_Operator - Production FPS 3"}'),
    ('POSITION_402', 'BS_Operator - Production FPS 4', 402, '{"legacy_sap_code": "BS_Operator - Production FPS 4"}'),
    ('POSITION_403', 'BS_Operator - Production FPS 6', 403, '{"legacy_sap_code": "BS_Operator - Production FPS 6"}'),
    ('POSITION_404', 'BS_Operator - Production FPS 7', 404, '{"legacy_sap_code": "BS_Operator - Production FPS 7"}'),
    ('POSITION_405', 'BS_Operator - Quality Control', 405, '{"legacy_sap_code": "BS_Operator - Quality Control"}'),
    ('POSITION_406', 'BS_Operator - Reception/Telp. Operator', 406, '{"legacy_sap_code": "BS_Operator - Reception/Telp. Operator"}'),
    ('POSITION_407', 'BS_Operator - Roll Mill', 407, '{"legacy_sap_code": "BS_Operator - Roll Mill"}'),
    ('POSITION_408', 'BS_Operator - Semolina Inventory Control', 408, '{"legacy_sap_code": "BS_Operator - Semolina Inventory Control"}'),
    ('POSITION_409', 'BS_Operator - Storage Delivery', 409, '{"legacy_sap_code": "BS_Operator - Storage Delivery"}'),
    ('POSITION_410', 'BS_Operator - Storage Production', 410, '{"legacy_sap_code": "BS_Operator - Storage Production"}'),
    ('POSITION_411', 'BS_Operator - Storage Support', 411, '{"legacy_sap_code": "BS_Operator - Storage Support"}'),
    ('POSITION_412', 'BS_Operator - Supplies Control', 412, '{"legacy_sap_code": "BS_Operator - Supplies Control"}'),
    ('POSITION_413', 'BS_Operator - Telephone & Receptionist', 413, '{"legacy_sap_code": "BS_Operator - Telephone & Receptionist"}'),
    ('POSITION_414', 'BS_Operator - Thermal', 414, '{"legacy_sap_code": "BS_Operator - Thermal"}'),
    ('POSITION_415', 'BS_Operator - Tubing', 415, '{"legacy_sap_code": "BS_Operator - Tubing"}'),
    ('POSITION_416', 'BS_Operator - Waste Management', 416, '{"legacy_sap_code": "BS_Operator - Waste Management"}'),
    ('POSITION_417', 'BS_Operator - Water Facility', 417, '{"legacy_sap_code": "BS_Operator - Water Facility"}'),
    ('POSITION_418', 'BS_Operator - Wheat Silo', 418, '{"legacy_sap_code": "BS_Operator - Wheat Silo"}'),
    ('POSITION_419', 'BS_Operator - Wheat Silo A', 419, '{"legacy_sap_code": "BS_Operator - Wheat Silo A"}'),
    ('POSITION_420', 'BS_Operator - Wheat Silo B', 420, '{"legacy_sap_code": "BS_Operator - Wheat Silo B"}'),
    ('POSITION_421', 'BS_Paramedics', 421, '{"legacy_sap_code": "BS_Paramedics"}'),
    ('POSITION_422', 'BS_Pjs. Manager - Security & Safety', 422, '{"legacy_sap_code": "BS_Pjs. Manager - Security & Safety"}'),
    ('POSITION_423', 'BS_Planner', 423, '{"legacy_sap_code": "BS_Planner"}'),
    ('POSITION_424', 'BS_Purchaser - Mechanical Parts', 424, '{"legacy_sap_code": "BS_Purchaser - Mechanical Parts"}'),
    ('POSITION_425', 'BS_Purchaser - Packaging Material', 425, '{"legacy_sap_code": "BS_Purchaser - Packaging Material"}'),
    ('POSITION_426', 'BS_Purchaser - Supporting Material', 426, '{"legacy_sap_code": "BS_Purchaser - Supporting Material"}'),
    ('POSITION_427', 'BS_Purchaser-Clearance &Factory Supplies', 427, '{"legacy_sap_code": "BS_Purchaser-Clearance &Factory Supplies"}'),
    ('POSITION_428', 'BS_Representative - Sales 1.1.1', 428, '{"legacy_sap_code": "BS_Representative - Sales 1.1.1"}'),
    ('POSITION_429', 'BS_Representative - Sales 1.1.2', 429, '{"legacy_sap_code": "BS_Representative - Sales 1.1.2"}'),
    ('POSITION_430', 'BS_Representative - Sales 1.2.1', 430, '{"legacy_sap_code": "BS_Representative - Sales 1.2.1"}'),
    ('POSITION_431', 'BS_Representative - Sales 1.3.1', 431, '{"legacy_sap_code": "BS_Representative - Sales 1.3.1"}'),
    ('POSITION_432', 'BS_Representative - Sales 1.4.1', 432, '{"legacy_sap_code": "BS_Representative - Sales 1.4.1"}'),
    ('POSITION_433', 'BS_Representative - Sales 2.1.1', 433, '{"legacy_sap_code": "BS_Representative - Sales 2.1.1"}'),
    ('POSITION_434', 'BS_Representative - Sales 2.1.2', 434, '{"legacy_sap_code": "BS_Representative - Sales 2.1.2"}'),
    ('POSITION_435', 'BS_Representative - Sales 2.2.1', 435, '{"legacy_sap_code": "BS_Representative - Sales 2.2.1"}'),
    ('POSITION_436', 'BS_Representative - Sales 2.2.2', 436, '{"legacy_sap_code": "BS_Representative - Sales 2.2.2"}'),
    ('POSITION_437', 'BS_Representative - Sales 2.3.1', 437, '{"legacy_sap_code": "BS_Representative - Sales 2.3.1"}'),
    ('POSITION_438', 'BS_Representative - Sales 2.3.2', 438, '{"legacy_sap_code": "BS_Representative - Sales 2.3.2"}'),
    ('POSITION_439', 'BS_Representative - Sales 3.1.1', 439, '{"legacy_sap_code": "BS_Representative - Sales 3.1.1"}'),
    ('POSITION_440', 'BS_Representative - Sales 3.1.2', 440, '{"legacy_sap_code": "BS_Representative - Sales 3.1.2"}'),
    ('POSITION_441', 'BS_Representative - Sales 3.1.3', 441, '{"legacy_sap_code": "BS_Representative - Sales 3.1.3"}'),
    ('POSITION_442', 'BS_Representative - Sales 3.2.1', 442, '{"legacy_sap_code": "BS_Representative - Sales 3.2.1"}'),
    ('POSITION_443', 'BS_Representative - Sales 3.2.3', 443, '{"legacy_sap_code": "BS_Representative - Sales 3.2.3"}'),
    ('POSITION_444', 'BS_Representative - Sales 3.3.2', 444, '{"legacy_sap_code": "BS_Representative - Sales 3.3.2"}'),
    ('POSITION_445', 'BS_SH - CP & Flour Premium Packing', 445, '{"legacy_sap_code": "BS_SH - CP & Flour Premium Packing"}'),
    ('POSITION_446', 'BS_SH - CP, Bulk & Jumbo Packing', 446, '{"legacy_sap_code": "BS_SH - CP, Bulk & Jumbo Packing"}'),
    ('POSITION_447', 'BS_SH - Education & Program Development', 447, '{"legacy_sap_code": "BS_SH - Education & Program Development"}'),
    ('POSITION_448', 'BS_SH - Financial accounting', 448, '{"legacy_sap_code": "BS_SH - Financial accounting"}'),
    ('POSITION_449', 'BS_SH - Flour Packg. & Supp. Material', 449, '{"legacy_sap_code": "BS_SH - Flour Packg. & Supp. Material"}'),
    ('POSITION_450', 'BS_SH - Information & Technology', 450, '{"legacy_sap_code": "BS_SH - Information & Technology"}'),
    ('POSITION_451', 'BS_SH - Line Maintenance Area Mills', 451, '{"legacy_sap_code": "BS_SH - Line Maintenance Area Mills"}'),
    ('POSITION_452', 'BS_SH - Line Maintenance Area Packing', 452, '{"legacy_sap_code": "BS_SH - Line Maintenance Area Packing"}'),
    ('POSITION_453', 'BS_SH - People & Org. Development', 453, '{"legacy_sap_code": "BS_SH - People & Org. Development"}'),
    ('POSITION_454', 'BS_SH - Product Development', 454, '{"legacy_sap_code": "BS_SH - Product Development"}'),
    ('POSITION_455', 'BS_SH - Purchasing', 455, '{"legacy_sap_code": "BS_SH - Purchasing"}'),
    ('POSITION_456', 'BS_SH - Shift Maintenance FMP & FSBP', 456, '{"legacy_sap_code": "BS_SH - Shift Maintenance FMP & FSBP"}'),
    ('POSITION_457', 'BS_SH - Spare Part & Material Stores', 457, '{"legacy_sap_code": "BS_SH - Spare Part & Material Stores"}'),
    ('POSITION_458', 'BS_SH - Water & Distribution Maintenance', 458, '{"legacy_sap_code": "BS_SH - Water & Distribution Maintenance"}'),
    ('POSITION_459', 'BS_SH -Compensation Admin. & Performance', 459, '{"legacy_sap_code": "BS_SH -Compensation Admin. & Performance"}'),
    ('POSITION_460', 'BS_SH-Flour Mixing,Premix & CP 1kg Plant', 460, '{"legacy_sap_code": "BS_SH-Flour Mixing,Premix & CP 1kg Plant"}'),
    ('POSITION_461', 'BS_SH-Gen. Affairs', 461, '{"legacy_sap_code": "BS_SH-Gen. Affairs"}'),
    ('POSITION_462', 'BS_SH-LM Area Intake & Wheat Silo-Mills', 462, '{"legacy_sap_code": "BS_SH-LM Area Intake & Wheat Silo-Mills"}'),
    ('POSITION_463', 'BS_SH-Marketing Data Analysis& Reporting', 463, '{"legacy_sap_code": "BS_SH-Marketing Data Analysis& Reporting"}'),
    ('POSITION_464', 'BS_SH-Outsource Mgmt & Factory Cleaning', 464, '{"legacy_sap_code": "BS_SH-Outsource Mgmt & Factory Cleaning"}'),
    ('POSITION_465', 'BS_SH-PPC', 465, '{"legacy_sap_code": "BS_SH-PPC"}'),
    ('POSITION_466', 'BS_SI - Flour Mixing,BP,CP,Bulk & Jumbo', 466, '{"legacy_sap_code": "BS_SI - Flour Mixing,BP,CP,Bulk & Jumbo"}'),
    ('POSITION_467', 'BS_SVP - Manufacturing', 467, '{"legacy_sap_code": "BS_SVP - Manufacturing"}'),
    ('POSITION_468', 'BS_Secretary - Pasta Plant', 468, '{"legacy_sap_code": "BS_Secretary - Pasta Plant"}'),
    ('POSITION_469', 'BS_Secretary - VP Engineering & Technolo', 469, '{"legacy_sap_code": "BS_Secretary - VP Engineering & Technolo"}'),
    ('POSITION_470', 'BS_Secretary SVP - Marketing', 470, '{"legacy_sap_code": "BS_Secretary SVP - Marketing"}'),
    ('POSITION_471', 'BS_Secretary VP Comptroller Jkt', 471, '{"legacy_sap_code": "BS_Secretary VP Comptroller Jkt"}'),
    ('POSITION_472', 'BS_Secretary VP Finance', 472, '{"legacy_sap_code": "BS_Secretary VP Finance"}'),
    ('POSITION_473', 'BS_Section Head - Accounting', 473, '{"legacy_sap_code": "BS_Section Head - Accounting"}'),
    ('POSITION_474', 'BS_Section Head - Accounts Payable', 474, '{"legacy_sap_code": "BS_Section Head - Accounts Payable"}'),
    ('POSITION_475', 'BS_Section Head - Accounts Payable  2', 475, '{"legacy_sap_code": "BS_Section Head - Accounts Payable  2"}'),
    ('POSITION_476', 'BS_Section Head - Accounts Receivable', 476, '{"legacy_sap_code": "BS_Section Head - Accounts Receivable"}'),
    ('POSITION_477', 'BS_Section Head - Automation', 477, '{"legacy_sap_code": "BS_Section Head - Automation"}'),
    ('POSITION_478', 'BS_Section Head - BMC Loyalti Program', 478, '{"legacy_sap_code": "BS_Section Head - BMC Loyalti Program"}'),
    ('POSITION_479', 'BS_Section Head - BMC Loyalti Program 1', 479, '{"legacy_sap_code": "BS_Section Head - BMC Loyalti Program 1"}'),
    ('POSITION_480', 'BS_Section Head - By Product Sales', 480, '{"legacy_sap_code": "BS_Section Head - By Product Sales"}'),
    ('POSITION_481', 'BS_Section Head - By-Product Packing', 481, '{"legacy_sap_code": "BS_Section Head - By-Product Packing"}'),
    ('POSITION_482', 'BS_Section Head - CP & Flour Premium Pac', 482, '{"legacy_sap_code": "BS_Section Head - CP & Flour Premium Pac"}'),
    ('POSITION_483', 'BS_Section Head - Calibration', 483, '{"legacy_sap_code": "BS_Section Head - Calibration"}'),
    ('POSITION_484', 'BS_Section Head - Career & People Mgt.', 484, '{"legacy_sap_code": "BS_Section Head - Career & People Mgt."}'),
    ('POSITION_485', 'BS_Section Head - Carpenter', 485, '{"legacy_sap_code": "BS_Section Head - Carpenter"}'),
    ('POSITION_486', 'BS_Section Head - Comp., Thermal & Dist.', 486, '{"legacy_sap_code": "BS_Section Head - Comp., Thermal & Dist."}'),
    ('POSITION_487', 'BS_Section Head - Compressor & Thermal S', 487, '{"legacy_sap_code": "BS_Section Head - Compressor & Thermal S"}'),
    ('POSITION_488', 'BS_Section Head - Costing', 488, '{"legacy_sap_code": "BS_Section Head - Costing"}'),
    ('POSITION_489', 'BS_Section Head - Costing & Inventory Co', 489, '{"legacy_sap_code": "BS_Section Head - Costing & Inventory Co"}'),
    ('POSITION_490', 'BS_Section Head - Credit, Billing & Coll', 490, '{"legacy_sap_code": "BS_Section Head - Credit, Billing & Coll"}'),
    ('POSITION_491', 'BS_Section Head - Delivery FPS', 491, '{"legacy_sap_code": "BS_Section Head - Delivery FPS"}'),
    ('POSITION_492', 'BS_Section Head - Depo & Adm. Area 1.4.1', 492, '{"legacy_sap_code": "BS_Section Head - Depo & Adm. Area 1.4.1"}'),
    ('POSITION_493', 'BS_Section Head - Depo & Adm. Area 1.4.2', 493, '{"legacy_sap_code": "BS_Section Head - Depo & Adm. Area 1.4.2"}'),
    ('POSITION_494', 'BS_Section Head - Depo & Admin. Area 1.3', 494, '{"legacy_sap_code": "BS_Section Head - Depo & Admin. Area 1.3"}'),
    ('POSITION_495', 'BS_Section Head - Depo & Admin. Area 3.1', 495, '{"legacy_sap_code": "BS_Section Head - Depo & Admin. Area 3.1"}'),
    ('POSITION_496', 'BS_Section Head - Depo & Admin. Area 3.3', 496, '{"legacy_sap_code": "BS_Section Head - Depo & Admin. Area 3.3"}'),
    ('POSITION_497', 'BS_Section Head - Electrical Services', 497, '{"legacy_sap_code": "BS_Section Head - Electrical Services"}'),
    ('POSITION_498', 'BS_Section Head - Employee Benefits', 498, '{"legacy_sap_code": "BS_Section Head - Employee Benefits"}'),
    ('POSITION_499', 'BS_Section Head - FPS - Tgr', 499, '{"legacy_sap_code": "BS_Section Head - FPS - Tgr"}'),
    ('POSITION_500', 'BS_Section Head - Fabrication & Fitting', 500, '{"legacy_sap_code": "BS_Section Head - Fabrication & Fitting"}'),
    ('POSITION_501', 'BS_Section Head - Financial Planning & S', 501, '{"legacy_sap_code": "BS_Section Head - Financial Planning & S"}'),
    ('POSITION_502', 'BS_Section Head - Finished Product Store', 502, '{"legacy_sap_code": "BS_Section Head - Finished Product Store"}'),
    ('POSITION_503', 'BS_Section Head - Fixed Asset Control -', 503, '{"legacy_sap_code": "BS_Section Head - Fixed Asset Control -"}'),
    ('POSITION_504', 'BS_Section Head - Flour Mixing', 504, '{"legacy_sap_code": "BS_Section Head - Flour Mixing"}'),
    ('POSITION_505', 'BS_Section Head - Flour Mixing & Packing', 505, '{"legacy_sap_code": "BS_Section Head - Flour Mixing & Packing"}'),
    ('POSITION_506', 'BS_Section Head - Flour Packing', 506, '{"legacy_sap_code": "BS_Section Head - Flour Packing"}'),
    ('POSITION_507', 'BS_Section Head - Flour Silo', 507, '{"legacy_sap_code": "BS_Section Head - Flour Silo"}'),
    ('POSITION_508', 'BS_Section Head - Flour Silo, Bulk & Jum', 508, '{"legacy_sap_code": "BS_Section Head - Flour Silo, Bulk & Jum"}'),
    ('POSITION_509', 'BS_Section Head - Fluting Services', 509, '{"legacy_sap_code": "BS_Section Head - Fluting Services"}'),
    ('POSITION_510', 'BS_Section Head - Gate Office - Sby', 510, '{"legacy_sap_code": "BS_Section Head - Gate Office - Sby"}'),
    ('POSITION_511', 'BS_Section Head - General Premises', 511, '{"legacy_sap_code": "BS_Section Head - General Premises"}'),
    ('POSITION_512', 'BS_Section Head - HR Admin.', 512, '{"legacy_sap_code": "BS_Section Head - HR Admin."}'),
    ('POSITION_513', 'BS_Section Head - Instrument', 513, '{"legacy_sap_code": "BS_Section Head - Instrument"}'),
    ('POSITION_514', 'BS_Section Head - Inter-island Operation', 514, '{"legacy_sap_code": "BS_Section Head - Inter-island Operation"}'),
    ('POSITION_515', 'BS_Section Head - Jetty Operations', 515, '{"legacy_sap_code": "BS_Section Head - Jetty Operations"}'),
    ('POSITION_516', 'BS_Section Head - LM Jetty A,Pelletizing', 516, '{"legacy_sap_code": "BS_Section Head - LM Jetty A,Pelletizing"}'),
    ('POSITION_517', 'BS_Section Head - LM Jetty Silo & Wheat', 517, '{"legacy_sap_code": "BS_Section Head - LM Jetty Silo & Wheat"}'),
    ('POSITION_518', 'BS_Section Head - LM Mill ABC, MTC, & FG', 518, '{"legacy_sap_code": "BS_Section Head - LM Mill ABC, MTC, & FG"}'),
    ('POSITION_519', 'BS_Section Head - LM Mill HIJ', 519, '{"legacy_sap_code": "BS_Section Head - LM Mill HIJ"}'),
    ('POSITION_520', 'BS_Section Head - LM Packing FMP', 520, '{"legacy_sap_code": "BS_Section Head - LM Packing FMP"}'),
    ('POSITION_521', 'BS_Section Head - LM Packing FSBP', 521, '{"legacy_sap_code": "BS_Section Head - LM Packing FSBP"}'),
    ('POSITION_522', 'BS_Section Head - LM Wheat Silo AB', 522, '{"legacy_sap_code": "BS_Section Head - LM Wheat Silo AB"}'),
    ('POSITION_523', 'BS_Section Head - Laminating', 523, '{"legacy_sap_code": "BS_Section Head - Laminating"}'),
    ('POSITION_524', 'BS_Section Head - Legal', 524, '{"legacy_sap_code": "BS_Section Head - Legal"}'),
    ('POSITION_525', 'BS_Section Head - Marketing', 525, '{"legacy_sap_code": "BS_Section Head - Marketing"}'),
    ('POSITION_526', 'BS_Section Head - Marketing Service Qual', 526, '{"legacy_sap_code": "BS_Section Head - Marketing Service Qual"}'),
    ('POSITION_527', 'BS_Section Head - Mill & Packing - Tgr', 527, '{"legacy_sap_code": "BS_Section Head - Mill & Packing - Tgr"}'),
    ('POSITION_528', 'BS_Section Head - Mill & Packing - Tgr B', 528, '{"legacy_sap_code": "BS_Section Head - Mill & Packing - Tgr B"}'),
    ('POSITION_529', 'BS_Section Head - Mill Support', 529, '{"legacy_sap_code": "BS_Section Head - Mill Support"}'),
    ('POSITION_530', 'BS_Section Head - Noodle & Bakery - Sby', 530, '{"legacy_sap_code": "BS_Section Head - Noodle & Bakery - Sby"}'),
    ('POSITION_531', 'BS_Section Head - Office Build.&Infrastr', 531, '{"legacy_sap_code": "BS_Section Head - Office Build.&Infrastr"}'),
    ('POSITION_532', 'BS_Section Head - Organization Analysis', 532, '{"legacy_sap_code": "BS_Section Head - Organization Analysis"}'),
    ('POSITION_533', 'BS_Section Head - Outgoing Gate Office', 533, '{"legacy_sap_code": "BS_Section Head - Outgoing Gate Office"}'),
    ('POSITION_534', 'BS_Section Head - PQC Laboratory', 534, '{"legacy_sap_code": "BS_Section Head - PQC Laboratory"}'),
    ('POSITION_535', 'BS_Section Head - PQC Laboratory Sby', 535, '{"legacy_sap_code": "BS_Section Head - PQC Laboratory Sby"}'),
    ('POSITION_536', 'BS_Section Head - Payment Executor', 536, '{"legacy_sap_code": "BS_Section Head - Payment Executor"}'),
    ('POSITION_537', 'BS_Section Head - Pellet Silo', 537, '{"legacy_sap_code": "BS_Section Head - Pellet Silo"}'),
    ('POSITION_538', 'BS_Section Head - Pelletizing', 538, '{"legacy_sap_code": "BS_Section Head - Pelletizing"}'),
    ('POSITION_539', 'BS_Section Head - Personnel Info System', 539, '{"legacy_sap_code": "BS_Section Head - Personnel Info System"}'),
    ('POSITION_540', 'BS_Section Head - Pest Control', 540, '{"legacy_sap_code": "BS_Section Head - Pest Control"}'),
    ('POSITION_541', 'BS_Section Head - Plant Builidng & Infra', 541, '{"legacy_sap_code": "BS_Section Head - Plant Builidng & Infra"}'),
    ('POSITION_542', 'BS_Section Head - Plant Engineering', 542, '{"legacy_sap_code": "BS_Section Head - Plant Engineering"}'),
    ('POSITION_543', 'BS_Section Head - Power Station', 543, '{"legacy_sap_code": "BS_Section Head - Power Station"}'),
    ('POSITION_544', 'BS_Section Head - Prod. Planning & Contr', 544, '{"legacy_sap_code": "BS_Section Head - Prod. Planning & Contr"}'),
    ('POSITION_545', 'BS_Section Head - Production FPS', 545, '{"legacy_sap_code": "BS_Section Head - Production FPS"}'),
    ('POSITION_546', 'BS_Section Head - Production Operation', 546, '{"legacy_sap_code": "BS_Section Head - Production Operation"}'),
    ('POSITION_547', 'BS_Section Head - QA & SHE', 547, '{"legacy_sap_code": "BS_Section Head - QA & SHE"}'),
    ('POSITION_548', 'BS_Section Head - QC Line', 548, '{"legacy_sap_code": "BS_Section Head - QC Line"}'),
    ('POSITION_549', 'BS_Section Head - Quality Assurance', 549, '{"legacy_sap_code": "BS_Section Head - Quality Assurance"}'),
    ('POSITION_550', 'BS_Section Head - Quality Assurance Sby', 550, '{"legacy_sap_code": "BS_Section Head - Quality Assurance Sby"}'),
    ('POSITION_551', 'BS_Section Head - Quality Assurance-Jkt', 551, '{"legacy_sap_code": "BS_Section Head - Quality Assurance-Jkt"}'),
    ('POSITION_552', 'BS_Section Head - Raw Material Planning', 552, '{"legacy_sap_code": "BS_Section Head - Raw Material Planning"}'),
    ('POSITION_553', 'BS_Section Head - Roll Mill', 553, '{"legacy_sap_code": "BS_Section Head - Roll Mill"}'),
    ('POSITION_554', 'BS_Section Head - SME Development - Sby', 554, '{"legacy_sap_code": "BS_Section Head - SME Development - Sby"}'),
    ('POSITION_555', 'BS_Section Head - Safety Operations', 555, '{"legacy_sap_code": "BS_Section Head - Safety Operations"}'),
    ('POSITION_556', 'BS_Section Head - Sales Admin.', 556, '{"legacy_sap_code": "BS_Section Head - Sales Admin."}'),
    ('POSITION_557', 'BS_Section Head - Sales Admin. - Sby', 557, '{"legacy_sap_code": "BS_Section Head - Sales Admin. - Sby"}'),
    ('POSITION_558', 'BS_Section Head - Sales Admin. 2', 558, '{"legacy_sap_code": "BS_Section Head - Sales Admin. 2"}'),
    ('POSITION_559', 'BS_Section Head - Sales Admin. 3', 559, '{"legacy_sap_code": "BS_Section Head - Sales Admin. 3"}'),
    ('POSITION_560', 'BS_Section Head - Security Operations', 560, '{"legacy_sap_code": "BS_Section Head - Security Operations"}'),
    ('POSITION_561', 'BS_Section Head - Storage Delivery', 561, '{"legacy_sap_code": "BS_Section Head - Storage Delivery"}'),
    ('POSITION_562', 'BS_Section Head - Supplies Inventory Con', 562, '{"legacy_sap_code": "BS_Section Head - Supplies Inventory Con"}'),
    ('POSITION_563', 'BS_Section Head - Thermal', 563, '{"legacy_sap_code": "BS_Section Head - Thermal"}'),
    ('POSITION_564', 'BS_Section Head - Waste Management', 564, '{"legacy_sap_code": "BS_Section Head - Waste Management"}'),
    ('POSITION_565', 'BS_Section Head - Water Supplies', 565, '{"legacy_sap_code": "BS_Section Head - Water Supplies"}'),
    ('POSITION_566', 'BS_Section Head - Wheat Silo', 566, '{"legacy_sap_code": "BS_Section Head - Wheat Silo"}'),
    ('POSITION_567', 'BS_Section Head - Wheat Silo A', 567, '{"legacy_sap_code": "BS_Section Head - Wheat Silo A"}'),
    ('POSITION_568', 'BS_Section Head - Wheat Silo B', 568, '{"legacy_sap_code": "BS_Section Head - Wheat Silo B"}'),
    ('POSITION_569', 'BS_Section Head -Security & Fire Brigade', 569, '{"legacy_sap_code": "BS_Section Head -Security & Fire Brigade"}'),
    ('POSITION_570', 'BS_Specialist - Org. HR & System Dev.', 570, '{"legacy_sap_code": "BS_Specialist - Org. HR & System Dev."}'),
    ('POSITION_571', 'BS_Specialist - Research & Development', 571, '{"legacy_sap_code": "BS_Specialist - Research & Development"}'),
    ('POSITION_572', 'BS_Sprintdnt-Jetty Op. & Wheat Silo', 572, '{"legacy_sap_code": "BS_Sprintdnt-Jetty Op. & Wheat Silo"}'),
    ('POSITION_573', 'BS_Spv - Finish Product', 573, '{"legacy_sap_code": "BS_Spv - Finish Product"}'),
    ('POSITION_574', 'BS_Spv. Auditor - Internal Audit', 574, '{"legacy_sap_code": "BS_Spv. Auditor - Internal Audit"}'),
    ('POSITION_575', 'BS_Sr. Specialist-Org. & HR System Dev.', 575, '{"legacy_sap_code": "BS_Sr. Specialist-Org. & HR System Dev."}'),
    ('POSITION_576', 'BS_Sr. Staff - A/P & Disbursement', 576, '{"legacy_sap_code": "BS_Sr. Staff - A/P & Disbursement"}'),
    ('POSITION_577', 'BS_Sr. Staff - BBC Report', 577, '{"legacy_sap_code": "BS_Sr. Staff - BBC Report"}'),
    ('POSITION_578', 'BS_Sr. Staff - By Product Domestic', 578, '{"legacy_sap_code": "BS_Sr. Staff - By Product Domestic"}'),
    ('POSITION_579', 'BS_Sr. Staff - End User & Network Suppor', 579, '{"legacy_sap_code": "BS_Sr. Staff - End User & Network Suppor"}'),
    ('POSITION_580', 'BS_Sr. Staff - Flour Export', 580, '{"legacy_sap_code": "BS_Sr. Staff - Flour Export"}'),
    ('POSITION_581', 'BS_Sr. Staff - IT Operations - Sby', 581, '{"legacy_sap_code": "BS_Sr. Staff - IT Operations - Sby"}'),
    ('POSITION_582', 'BS_Sr. Staff - Insurance Admin', 582, '{"legacy_sap_code": "BS_Sr. Staff - Insurance Admin"}'),
    ('POSITION_583', 'BS_Sr. Staff - Key Account High Class Ou', 583, '{"legacy_sap_code": "BS_Sr. Staff - Key Account High Class Ou"}'),
    ('POSITION_584', 'BS_Sr. Staff - Legal & License - Sby', 584, '{"legacy_sap_code": "BS_Sr. Staff - Legal & License - Sby"}'),
    ('POSITION_585', 'BS_Sr. Staff - Management Accounting', 585, '{"legacy_sap_code": "BS_Sr. Staff - Management Accounting"}'),
    ('POSITION_586', 'BS_Sr. Staff - Noodle & Bakery', 586, '{"legacy_sap_code": "BS_Sr. Staff - Noodle & Bakery"}'),
    ('POSITION_587', 'BS_Sr. Staff - Org. Planning & Analysis', 587, '{"legacy_sap_code": "BS_Sr. Staff - Org. Planning & Analysis"}'),
    ('POSITION_588', 'BS_Sr. Staff - PPIC - Tgr', 588, '{"legacy_sap_code": "BS_Sr. Staff - PPIC - Tgr"}'),
    ('POSITION_589', 'BS_Sr. Staff - Payroll Support', 589, '{"legacy_sap_code": "BS_Sr. Staff - Payroll Support"}'),
    ('POSITION_590', 'BS_Sr. Staff - Proper & Sustainability', 590, '{"legacy_sap_code": "BS_Sr. Staff - Proper & Sustainability"}'),
    ('POSITION_591', 'BS_Sr. Staff - Quality Control - Tgr', 591, '{"legacy_sap_code": "BS_Sr. Staff - Quality Control - Tgr"}'),
    ('POSITION_592', 'BS_Sr. Staff - Recruitment', 592, '{"legacy_sap_code": "BS_Sr. Staff - Recruitment"}'),
    ('POSITION_593', 'BS_Sr. Staff - System Support', 593, '{"legacy_sap_code": "BS_Sr. Staff - System Support"}'),
    ('POSITION_594', 'BS_Sr. Staff - Tax', 594, '{"legacy_sap_code": "BS_Sr. Staff - Tax"}'),
    ('POSITION_595', 'BS_Sr. Supervisor - Project', 595, '{"legacy_sap_code": "BS_Sr. Supervisor - Project"}'),
    ('POSITION_596', 'BS_Sr. Technician - LM Mill DE & KL', 596, '{"legacy_sap_code": "BS_Sr. Technician - LM Mill DE & KL"}'),
    ('POSITION_597', 'BS_Sr. Technician - LM Mill MNO', 597, '{"legacy_sap_code": "BS_Sr. Technician - LM Mill MNO"}'),
    ('POSITION_598', 'BS_Sr. Technician - Shift CK Maint. Mill', 598, '{"legacy_sap_code": "BS_Sr. Technician - Shift CK Maint. Mill"}'),
    ('POSITION_599', 'BS_Sr. Technician - Shift KB Maint. Mill', 599, '{"legacy_sap_code": "BS_Sr. Technician - Shift KB Maint. Mill"}'),
    ('POSITION_600', 'BS_Sr. Technicians - Calibration', 600, '{"legacy_sap_code": "BS_Sr. Technicians - Calibration"}'),
    ('POSITION_601', 'BS_Sr. Technicians - Instrument', 601, '{"legacy_sap_code": "BS_Sr. Technicians - Instrument"}'),
    ('POSITION_602', 'BS_Sr. Technicians - Office Build.&Infr.', 602, '{"legacy_sap_code": "BS_Sr. Technicians - Office Build.&Infr."}'),
    ('POSITION_603', 'BS_Sr. Technicians - Power & Distributio', 603, '{"legacy_sap_code": "BS_Sr. Technicians - Power & Distributio"}'),
    ('POSITION_604', 'BS_Sr. Technicians - Power Supplies', 604, '{"legacy_sap_code": "BS_Sr. Technicians - Power Supplies"}'),
    ('POSITION_605', 'BS_Sr.Staff-Safety & Environment Assuran', 605, '{"legacy_sap_code": "BS_Sr.Staff-Safety & Environment Assuran"}'),
    ('POSITION_606', 'BS_Sr.Technician - Fabrication & Fitting', 606, '{"legacy_sap_code": "BS_Sr.Technician - Fabrication & Fitting"}'),
    ('POSITION_607', 'BS_Staff - A/R & Collection', 607, '{"legacy_sap_code": "BS_Staff - A/R & Collection"}'),
    ('POSITION_608', 'BS_Staff - Account Admin.', 608, '{"legacy_sap_code": "BS_Staff - Account Admin."}'),
    ('POSITION_609', 'BS_Staff - Administration', 609, '{"legacy_sap_code": "BS_Staff - Administration"}'),
    ('POSITION_610', 'BS_Staff - Administration Marketing 1.4', 610, '{"legacy_sap_code": "BS_Staff - Administration Marketing 1.4"}'),
    ('POSITION_611', 'BS_Staff - Advertising & Promotion', 611, '{"legacy_sap_code": "BS_Staff - Advertising & Promotion"}'),
    ('POSITION_612', 'BS_Staff - Analysis & Reporting', 612, '{"legacy_sap_code": "BS_Staff - Analysis & Reporting"}'),
    ('POSITION_613', 'BS_Staff - BBC Coordinator - Sby 3', 613, '{"legacy_sap_code": "BS_Staff - BBC Coordinator - Sby 3"}'),
    ('POSITION_614', 'BS_Staff - BMC Loyalti Program - Sby 1', 614, '{"legacy_sap_code": "BS_Staff - BMC Loyalti Program - Sby 1"}'),
    ('POSITION_615', 'BS_Staff - Benefit Admin.', 615, '{"legacy_sap_code": "BS_Staff - Benefit Admin."}'),
    ('POSITION_616', 'BS_Staff - Benefits Admin.', 616, '{"legacy_sap_code": "BS_Staff - Benefits Admin."}'),
    ('POSITION_617', 'BS_Staff - Complaint Handling - Sby', 617, '{"legacy_sap_code": "BS_Staff - Complaint Handling - Sby"}'),
    ('POSITION_618', 'BS_Staff - Education & Program Dev.', 618, '{"legacy_sap_code": "BS_Staff - Education & Program Dev."}'),
    ('POSITION_619', 'BS_Staff - Employee Records', 619, '{"legacy_sap_code": "BS_Staff - Employee Records"}'),
    ('POSITION_620', 'BS_Staff - End Product/Baker', 620, '{"legacy_sap_code": "BS_Staff - End Product/Baker"}'),
    ('POSITION_621', 'BS_Staff - Factory Cleaning', 621, '{"legacy_sap_code": "BS_Staff - Factory Cleaning"}'),
    ('POSITION_622', 'BS_Staff - Fixed Asset - Sby', 622, '{"legacy_sap_code": "BS_Staff - Fixed Asset - Sby"}'),
    ('POSITION_623', 'BS_Staff - Gate Office 1.1', 623, '{"legacy_sap_code": "BS_Staff - Gate Office 1.1"}'),
    ('POSITION_624', 'BS_Staff - Gate Office 1.2.1', 624, '{"legacy_sap_code": "BS_Staff - Gate Office 1.2.1"}'),
    ('POSITION_625', 'BS_Staff - Gate Office 1.4.1', 625, '{"legacy_sap_code": "BS_Staff - Gate Office 1.4.1"}'),
    ('POSITION_626', 'BS_Staff - Gate Office 3.3.1', 626, '{"legacy_sap_code": "BS_Staff - Gate Office 3.3.1"}'),
    ('POSITION_627', 'BS_Staff - Gate Office 3.3.2', 627, '{"legacy_sap_code": "BS_Staff - Gate Office 3.3.2"}'),
    ('POSITION_628', 'BS_Staff - Industrial Relations', 628, '{"legacy_sap_code": "BS_Staff - Industrial Relations"}'),
    ('POSITION_629', 'BS_Staff - Inter-island Admin.', 629, '{"legacy_sap_code": "BS_Staff - Inter-island Admin."}'),
    ('POSITION_630', 'BS_Staff - Management Accounting', 630, '{"legacy_sap_code": "BS_Staff - Management Accounting"}'),
    ('POSITION_631', 'BS_Staff - Organization Analysis', 631, '{"legacy_sap_code": "BS_Staff - Organization Analysis"}'),
    ('POSITION_632', 'BS_Staff - Organization Development', 632, '{"legacy_sap_code": "BS_Staff - Organization Development"}'),
    ('POSITION_633', 'BS_Staff - Personnel Information', 633, '{"legacy_sap_code": "BS_Staff - Personnel Information"}'),
    ('POSITION_634', 'BS_Staff - Purchasing Admin & Clearance', 634, '{"legacy_sap_code": "BS_Staff - Purchasing Admin & Clearance"}'),
    ('POSITION_635', 'BS_Staff - Recruitment & Training', 635, '{"legacy_sap_code": "BS_Staff - Recruitment & Training"}'),
    ('POSITION_636', 'BS_Staff - Salary Admin.', 636, '{"legacy_sap_code": "BS_Staff - Salary Admin."}'),
    ('POSITION_637', 'BS_Staff - Sales Admin.', 637, '{"legacy_sap_code": "BS_Staff - Sales Admin."}'),
    ('POSITION_638', 'BS_Staff - Training Management', 638, '{"legacy_sap_code": "BS_Staff - Training Management"}'),
    ('POSITION_639', 'BS_Staff - Transportation incl. Bulk - S', 639, '{"legacy_sap_code": "BS_Staff - Transportation incl. Bulk - S"}'),
    ('POSITION_640', 'BS_Staff Admin - Jetty & Silo', 640, '{"legacy_sap_code": "BS_Staff Admin - Jetty & Silo"}'),
    ('POSITION_641', 'BS_Staff Admin. - FSBP', 641, '{"legacy_sap_code": "BS_Staff Admin. - FSBP"}'),
    ('POSITION_642', 'BS_Staff-A&P Souvenir & Office Supplies', 642, '{"legacy_sap_code": "BS_Staff-A&P Souvenir & Office Supplies"}'),
    ('POSITION_643', 'BS_Staff-Outsource Mgmt&Factory Cleaning', 643, '{"legacy_sap_code": "BS_Staff-Outsource Mgmt&Factory Cleaning"}'),
    ('POSITION_644', 'BS_Staff. Purchasing', 644, '{"legacy_sap_code": "BS_Staff. Purchasing"}'),
    ('POSITION_645', 'BS_Stores Keeper - Production Supplies S', 645, '{"legacy_sap_code": "BS_Stores Keeper - Production Supplies S"}'),
    ('POSITION_646', 'BS_Sup - Shift Extruder', 646, '{"legacy_sap_code": "BS_Sup - Shift Extruder"}'),
    ('POSITION_647', 'BS_Sup Staff - Project & Develop. Eng.', 647, '{"legacy_sap_code": "BS_Sup Staff - Project & Develop. Eng."}'),
    ('POSITION_648', 'BS_Superintendent - Dev. Engineering Sby', 648, '{"legacy_sap_code": "BS_Superintendent - Dev. Engineering Sby"}'),
    ('POSITION_649', 'BS_Superintendent - Flour & By-Product P', 649, '{"legacy_sap_code": "BS_Superintendent - Flour & By-Product P"}'),
    ('POSITION_650', 'BS_Superintendent - Flour Mixing, CP & P', 650, '{"legacy_sap_code": "BS_Superintendent - Flour Mixing, CP & P"}'),
    ('POSITION_651', 'BS_Superintendent - Flour Silo & Packing', 651, '{"legacy_sap_code": "BS_Superintendent - Flour Silo & Packing"}'),
    ('POSITION_652', 'BS_Superintendent - Flour Silo, Bulk & J', 652, '{"legacy_sap_code": "BS_Superintendent - Flour Silo, Bulk & J"}'),
    ('POSITION_653', 'BS_Superintendent - Jetty & Silo', 653, '{"legacy_sap_code": "BS_Superintendent - Jetty & Silo"}'),
    ('POSITION_654', 'BS_Superintendent - Line Maintenance', 654, '{"legacy_sap_code": "BS_Superintendent - Line Maintenance"}'),
    ('POSITION_655', 'BS_Superintendent - Material Stores - Sb', 655, '{"legacy_sap_code": "BS_Superintendent - Material Stores - Sb"}'),
    ('POSITION_656', 'BS_Superintendent - Pelletizing', 656, '{"legacy_sap_code": "BS_Superintendent - Pelletizing"}'),
    ('POSITION_657', 'BS_Superintendent - Production - Tgr', 657, '{"legacy_sap_code": "BS_Superintendent - Production - Tgr"}'),
    ('POSITION_658', 'BS_Superintendent - Utility & Facility', 658, '{"legacy_sap_code": "BS_Superintendent - Utility & Facility"}'),
    ('POSITION_659', 'BS_Superintendent - Workshop', 659, '{"legacy_sap_code": "BS_Superintendent - Workshop"}'),
    ('POSITION_660', 'BS_Superintendent-Pellet Silo & Handling', 660, '{"legacy_sap_code": "BS_Superintendent-Pellet Silo & Handling"}'),
    ('POSITION_661', 'BS_Supervisor - Financial Acc', 661, '{"legacy_sap_code": "BS_Supervisor - Financial Acc"}'),
    ('POSITION_662', 'BS_Supervisor - M&R Converter', 662, '{"legacy_sap_code": "BS_Supervisor - M&R Converter"}'),
    ('POSITION_663', 'BS_Supervisor - PPC', 663, '{"legacy_sap_code": "BS_Supervisor - PPC"}'),
    ('POSITION_664', 'BS_Supervisor - Shift Laminating', 664, '{"legacy_sap_code": "BS_Supervisor - Shift Laminating"}'),
    ('POSITION_665', 'BS_Supervisor - Techn. Circular', 665, '{"legacy_sap_code": "BS_Supervisor - Techn. Circular"}'),
    ('POSITION_666', 'BS_Supervisor - Technician Extruder', 666, '{"legacy_sap_code": "BS_Supervisor - Technician Extruder"}'),
    ('POSITION_667', 'BS_Supervisor Sift Tubing', 667, '{"legacy_sap_code": "BS_Supervisor Sift Tubing"}'),
    ('POSITION_668', 'BS_Supervisor- Shift Converting', 668, '{"legacy_sap_code": "BS_Supervisor- Shift Converting"}'),
    ('POSITION_669', 'BS_Support Staff - Area Sales 1.1', 669, '{"legacy_sap_code": "BS_Support Staff - Area Sales 1.1"}'),
    ('POSITION_670', 'BS_Support Staff - Area Sales 3.2', 670, '{"legacy_sap_code": "BS_Support Staff - Area Sales 3.2"}'),
    ('POSITION_671', 'BS_Support Staff - Jetty & Silo', 671, '{"legacy_sap_code": "BS_Support Staff - Jetty & Silo"}'),
    ('POSITION_672', 'BS_Support Staff - Kepala Divisi', 672, '{"legacy_sap_code": "BS_Support Staff - Kepala Divisi"}'),
    ('POSITION_673', 'BS_Support Staff - Manufacturing', 673, '{"legacy_sap_code": "BS_Support Staff - Manufacturing"}'),
    ('POSITION_674', 'BS_Support Staff - Mill 2', 674, '{"legacy_sap_code": "BS_Support Staff - Mill 2"}'),
    ('POSITION_675', 'BS_Support Staff - QPD', 675, '{"legacy_sap_code": "BS_Support Staff - QPD"}'),
    ('POSITION_676', 'BS_Support Staff - Workshop & Plant Infr', 676, '{"legacy_sap_code": "BS_Support Staff - Workshop & Plant Infr"}'),
    ('POSITION_677', 'BS_Support Staff-Material Stor&Waste Mgt', 677, '{"legacy_sap_code": "BS_Support Staff-Material Stor&Waste Mgt"}'),
    ('POSITION_678', 'BS_Technician - Automation', 678, '{"legacy_sap_code": "BS_Technician - Automation"}'),
    ('POSITION_679', 'BS_Technician - Circular', 679, '{"legacy_sap_code": "BS_Technician - Circular"}'),
    ('POSITION_680', 'BS_Technician - Extruder', 680, '{"legacy_sap_code": "BS_Technician - Extruder"}'),
    ('POSITION_681', 'BS_Technician - M&R Converter', 681, '{"legacy_sap_code": "BS_Technician - M&R Converter"}'),
    ('POSITION_682', 'BS_Technician - M&R Electric', 682, '{"legacy_sap_code": "BS_Technician - M&R Electric"}'),
    ('POSITION_683', 'BS_Technicians - Compressor & Thermal Su', 683, '{"legacy_sap_code": "BS_Technicians - Compressor & Thermal Su"}'),
    ('POSITION_684', 'BS_Technicians - Electrical Services', 684, '{"legacy_sap_code": "BS_Technicians - Electrical Services"}'),
    ('POSITION_685', 'BS_Technicians - Fabrication & Fitting', 685, '{"legacy_sap_code": "BS_Technicians - Fabrication & Fitting"}'),
    ('POSITION_686', 'BS_Technicians - Fluting Services', 686, '{"legacy_sap_code": "BS_Technicians - Fluting Services"}'),
    ('POSITION_687', 'BS_Technicians - Garage & Heavy Equip.', 687, '{"legacy_sap_code": "BS_Technicians - Garage & Heavy Equip."}'),
    ('POSITION_688', 'BS_Technicians - LM Jetty A,Pelletizing&', 688, '{"legacy_sap_code": "BS_Technicians - LM Jetty A,Pelletizing&"}'),
    ('POSITION_689', 'BS_Technicians - LM Mill ABC, MTC, & FG', 689, '{"legacy_sap_code": "BS_Technicians - LM Mill ABC, MTC, & FG"}'),
    ('POSITION_690', 'BS_Technicians - LM Mill DE & KL', 690, '{"legacy_sap_code": "BS_Technicians - LM Mill DE & KL"}'),
    ('POSITION_691', 'BS_Technicians - LM Mill HIJ', 691, '{"legacy_sap_code": "BS_Technicians - LM Mill HIJ"}'),
    ('POSITION_692', 'BS_Technicians - LM Mill MNO', 692, '{"legacy_sap_code": "BS_Technicians - LM Mill MNO"}'),
    ('POSITION_693', 'BS_Technicians - LM Packing FMP', 693, '{"legacy_sap_code": "BS_Technicians - LM Packing FMP"}'),
    ('POSITION_694', 'BS_Technicians - LM Roll Mill', 694, '{"legacy_sap_code": "BS_Technicians - LM Roll Mill"}'),
    ('POSITION_695', 'BS_Technicians - Machining & Repair', 695, '{"legacy_sap_code": "BS_Technicians - Machining & Repair"}'),
    ('POSITION_696', 'BS_Technicians - Plant Build. & Infrastr', 696, '{"legacy_sap_code": "BS_Technicians - Plant Build. & Infrastr"}'),
    ('POSITION_697', 'BS_Technicians - Shift A Maintenance Jet', 697, '{"legacy_sap_code": "BS_Technicians - Shift A Maintenance Jet"}'),
    ('POSITION_698', 'BS_Technicians - Shift B Maintenance Jet', 698, '{"legacy_sap_code": "BS_Technicians - Shift B Maintenance Jet"}'),
    ('POSITION_699', 'BS_Technicians - Shift C Maint. FMP&FSBP', 699, '{"legacy_sap_code": "BS_Technicians - Shift C Maint. FMP&FSBP"}'),
    ('POSITION_700', 'BS_Technicians - Shift CK Maint. Mill', 700, '{"legacy_sap_code": "BS_Technicians - Shift CK Maint. Mill"}'),
    ('POSITION_701', 'BS_Technicians - Shift KB Maint. Mill', 701, '{"legacy_sap_code": "BS_Technicians - Shift KB Maint. Mill"}'),
    ('POSITION_702', 'BS_Technicians - Shift SB Maint. Mill', 702, '{"legacy_sap_code": "BS_Technicians - Shift SB Maint. Mill"}'),
    ('POSITION_703', 'BS_Technicians - Water Supplies', 703, '{"legacy_sap_code": "BS_Technicians - Water Supplies"}'),
    ('POSITION_704', 'BS_Technicion - Circular', 704, '{"legacy_sap_code": "BS_Technicion - Circular"}'),
    ('POSITION_705', 'BS_Technicion - Circular Jumbo', 705, '{"legacy_sap_code": "BS_Technicion - Circular Jumbo"}'),
    ('POSITION_706', 'BS_Technicion - Extruder', 706, '{"legacy_sap_code": "BS_Technicion - Extruder"}'),
    ('POSITION_707', 'BS_VP - Area Sales 3', 707, '{"legacy_sap_code": "BS_VP - Area Sales 3"}'),
    ('POSITION_708', 'BS_VP - Cibitung Plant', 708, '{"legacy_sap_code": "BS_VP - Cibitung Plant"}'),
    ('POSITION_709', 'BS_VP - Comptroller - Sby', 709, '{"legacy_sap_code": "BS_VP - Comptroller - Sby"}'),
    ('POSITION_710', 'BS_VP - Finance', 710, '{"legacy_sap_code": "BS_VP - Finance"}'),
    ('POSITION_711', 'BS_VP - HR Flour - Jkt', 711, '{"legacy_sap_code": "BS_VP - HR Flour - Jkt"}'),
    ('POSITION_712', 'BS_VP - Operations - Sby', 712, '{"legacy_sap_code": "BS_VP - Operations - Sby"}')
) AS v(code, name, sort_order, metadata)
WHERE c.code = 'POSITION'
ON CONFLICT (category_id, COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), code)
    WHERE deleted_at IS NULL DO NOTHING;
