DELETE FROM masterdata_items
WHERE category_id IN (
    SELECT id FROM masterdata_categories
    WHERE code IN (
        'PROVINCE', 'NATIONALITY', 'TAX_STATUS', 'TERMINATION_REASON',
        'LEGAL_ENTITY', 'BUSINESS_UNIT', 'WORK_LOCATION',
        'DIVISION', 'DEPARTMENT_FUNCTION', 'POSITION'
    )
);

DELETE FROM masterdata_categories
WHERE code IN (
    'PROVINCE', 'NATIONALITY', 'TAX_STATUS', 'TERMINATION_REASON',
    'LEGAL_ENTITY', 'BUSINESS_UNIT', 'WORK_LOCATION',
    'DIVISION', 'DEPARTMENT_FUNCTION', 'POSITION'
);
