-- ============================================================================
-- SEED: ORGANIZATION Category and Items (Hierarchical under TENANT_TYPE)
-- Description: Creates ORGANIZATION category and seeds organizations
--              following the cascading dropdown pattern:
--              TENANT_TYPE (dropdown 1) → ORGANIZATION (dropdown 2)
-- Note: UUIDs are generated by PostgreSQL 18+ via uuidv7()
-- ============================================================================

DO $$
DECLARE
    v_tenant_type_category_id UUID;
    v_organization_category_id UUID;
    v_mitra_pendiri_item_id UUID;
    v_pension_fund_item_id UUID;
BEGIN
    -- 1. Get TENANT_TYPE category ID (parent category for ORGANIZATION)
    SELECT id INTO v_tenant_type_category_id
    FROM masterdata_categories
    WHERE code = 'TENANT_TYPE' AND deleted_at IS NULL;

    IF v_tenant_type_category_id IS NULL THEN
        RAISE EXCEPTION 'TENANT_TYPE category not found. Run migration 000026 first.';
    END IF;

    -- 2. Get TENANT_TYPE items (parents for organizations)
    SELECT id INTO v_mitra_pendiri_item_id
    FROM masterdata_items
    WHERE category_id = v_tenant_type_category_id
      AND code = 'MITRA_PENDIRI'
      AND deleted_at IS NULL;

    SELECT id INTO v_pension_fund_item_id
    FROM masterdata_items
    WHERE category_id = v_tenant_type_category_id
      AND code = 'PENSION_FUND'
      AND deleted_at IS NULL;

    IF v_mitra_pendiri_item_id IS NULL OR v_pension_fund_item_id IS NULL THEN
        RAISE EXCEPTION 'TENANT_TYPE items not found. Run migration 000026 first.';
    END IF;

    -- 3. Create ORGANIZATION category (child of TENANT_TYPE)
    INSERT INTO masterdata_categories (
        code, name, description,
        parent_category_id,
        is_system, is_tenant_extensible,
        sort_order, status, metadata
    ) VALUES (
        'ORGANIZATION',
        'Organization',
        'Organizations/companies within each tenant type',
        v_tenant_type_category_id,  -- parent category = TENANT_TYPE
        TRUE,                        -- system category
        FALSE,                       -- NOT tenant-extensible (platform-level only)
        101,                         -- sort order (after TENANT_TYPE)
        'ACTIVE',
        '{}'::jsonb
    )
    RETURNING id INTO v_organization_category_id;

    -- 4. Seed MITRA_PENDIRI organizations
    INSERT INTO masterdata_items (
        category_id, tenant_id, parent_item_id,
        code, name, alt_name, description,
        sort_order, is_system, is_default, status, metadata
    ) VALUES
        (v_organization_category_id, NULL, v_mitra_pendiri_item_id,
         'ISM-BOGASARI', 'PT ISM Bogasari Flour Mills', 'ISM Bogasari',
         'Flour milling company under Mitra Pendiri',
         1, TRUE, FALSE, 'ACTIVE',
         '{"company_type": "PT", "industry": "food_manufacturing"}'::jsonb),

        (v_organization_category_id, NULL, v_mitra_pendiri_item_id,
         'INTI-ABADI-KEMASINDO', 'PT Inti Abadi Kemasindo', 'IAK',
         'Packaging company under Mitra Pendiri',
         2, TRUE, FALSE, 'ACTIVE',
         '{"company_type": "PT", "industry": "packaging"}'::jsonb);

    -- 5. Seed PENSION_FUND organizations
    INSERT INTO masterdata_items (
        category_id, tenant_id, parent_item_id,
        code, name, alt_name, description,
        sort_order, is_system, is_default, status, metadata
    ) VALUES
        (v_organization_category_id, NULL, v_pension_fund_item_id,
         'DPIP-BOGASARI', 'DPIP Bogasari', 'DPIP',
         'Dana Pensiun Iuran Pasti Bogasari',
         1, TRUE, FALSE, 'ACTIVE',
         '{"pension_type": "defined_contribution"}'::jsonb),

        (v_organization_category_id, NULL, v_pension_fund_item_id,
         'DPMP-BOGASARI', 'DPMP Bogasari', 'DPMP',
         'Dana Pensiun Manfaat Pasti Bogasari',
         2, TRUE, FALSE, 'ACTIVE',
         '{"pension_type": "defined_benefit"}'::jsonb);

    RAISE NOTICE 'Seeded ORGANIZATION category with 4 items (2 under MITRA_PENDIRI, 2 under PENSION_FUND)';
END $$;
